"""
Atmospheric Complexity Framework (ACF)

Meteorological Satellite Remote Sensing, Spectral Channels & Algorithms Encyclopedia Module
"""

from typing import List
from acf.science.encyclopedia.entry import EncyclopediaEntry
from acf.science.encyclopedia.registry import EncyclopediaRegistry

ENTRIES: List[EncyclopediaEntry] = [
    # --- SATELLITES ---
    EncyclopediaEntry(
        key="sat_meteosat_series",
        name="Satellites Météorologiques Meteosat (EUMETSAT)",
        domain="Satellites Météorologiques",
        subdomain="Plates-formes géostationnaires",
        equation="Position: 0° Longitude / 45°E, Imagerie toutes les 10-15 min (SEVIRI) / 2.5-10 min (FCI MTG)",
        latex_equation=r"\text{Meteosat (MSG / MTG)} \quad h_{\text{orbit}} = 35786 \text{ km}",
        variables={"Instruments": "SEVIRI (MSG) / FCI & LI (MTG)", "Résolution": "1 km à 3 km"},
        units={"Résolution": "km"},
        description="Série de satellites géostationnaires européens exploités par EUMETSAT assurant la couverture continue de l'Europe, de l'Afrique et de l'Océan Atlantique.",
        application_conditions=["Suivi du temps en temps réel (Nowcasting) et prévision numérique"],
        limitations=["Résolution spatiale se dégradant vers les hautes latitudes polaires"],
        references=["EUMETSAT Meteosat User Guide", "WMO Satellite Directory"],
    ),
    EncyclopediaEntry(
        key="sat_goes_series",
        name="Satellites GOES (NOAA / NASA)",
        domain="Satellites Météorologiques",
        subdomain="Plates-formes géostationnaires",
        equation="Position: GOES-East (75°W) et GOES-West (137°W)",
        latex_equation=r"\text{GOES-R Series (16, 17, 18)} \quad h = 35786 \text{ km}",
        variables={"Instruments": "ABI (Advanced Baseline Imager), GLM (Geostationary Lightning Mapper)"},
        units={"Canaux": "16 bandes spectrales"},
        description="Satellites géostationnaires américains de la NOAA assurant la surveillance en continu des Amériques et du Pacifique/Atlantique avec imagerie ultra-rapide (30 secondes en mode mesoscale).",
        application_conditions=["Suivi des ouragans, orages violents, feux de forêt et foudre"],
        limitations=["Couverture limitée aux Amériques et Pacifique"],
        references=["NOAA NESDIS GOES-R Documentation", "AMS Satellite Meteorology"],
    ),
    EncyclopediaEntry(
        key="sat_himawari_series",
        name="Satellites Himawari (JMA - Agence Météorologique du Japon)",
        domain="Satellites Météorologiques",
        subdomain="Plates-formes géostationnaires",
        equation="Position: 140.7°E (Pacifique Ouest et Asie de l'Est)",
        latex_equation=r"\text{Himawari-8/9 (AHI)} \quad h = 35786 \text{ km}",
        variables={"Instrument": "AHI (Advanced Himawari Imager - 16 canaux)"},
        units={"Fréquence": "10 min globe / 2.5 min Japon"},
        description="Satellites géostationnaires japonais couvrant l'Asie de l'Est, l'Australie et le Pacifique Ouest pour le suivi des typhons et de l'activité convective.",
        application_conditions=["Suivi des typhons et moussons asiatiques"],
        limitations=["Zone de couverture centrée sur l'Asie-Pacifique"],
        references=["JMA Himawari User Guide", "WMO Satellite Products"],
    ),
    EncyclopediaEntry(
        key="sat_modis_instrument",
        name="Spectroradiomètre MODIS (NASA Terra & Aqua)",
        domain="Satellites Météorologiques",
        subdomain="Plates-formes défilantes polar-orbiting",
        equation="Orbit: Héliosynchrone à 705 km, 36 bandes spectrales (0.4 µm à 14.4 µm)",
        latex_equation=r"\text{MODIS (Terra/Aqua)} \quad h_{\text{orbit}} = 705 \text{ km}, \quad \text{Swath} = 2330 \text{ km}",
        variables={"Résolution": "250m, 500m, 1000m"},
        units={"Résolution": "m"},
        description="Instrument scientifique embarqué sur les satellites défilants NASA Terra et Aqua fournissant des observations globales à haute résolution spatiale pour les nuages, les aérosols et la surface.",
        application_conditions=["Recherche scientifique, propriétés optiques des nuages et aérosols"],
        limitations=["Passages uniquement 2 fois par jour par endroit (faible fréquence temporelle)"],
        references=["NASA MODIS ATBD Documentation", "Salomonson et al. (1989)"],
    ),
    EncyclopediaEntry(
        key="sat_viirs_instrument",
        name="Instrument VIIRS (NOAA / NASA Suomi-NPP & JPSS)",
        domain="Satellites Météorologiques",
        subdomain="Plates-formes défilantes polar-orbiting",
        equation="22 bandes spectrales dont la bande nocturne DNB (Day/Night Band)",
        latex_equation=r"\text{VIIRS (JPSS)} \quad h = 824 \text{ km}, \quad \text{Swath} = 3040 \text{ km}",
        variables={"DNB": "Imagerie nocturne sous lumière lunaire / éclairage urbain"},
        units={"Canaux": "22 canaux M/I/DNB"},
        description="Radiomètre radiométrique de nouvelle génération assurant la continuité des mesures MODIS/AVHRR pour les modèles de prévision numérique et le suivi nocturne des nuages et brouillards.",
        application_conditions=["Prévision numérique du temps et observation polaire nocturne"],
        limitations=["Satellite polaire défilant"],
        references=["NOAA NESDIS VIIRS Technical Documentation", "AMS Remote Sensing"],
    ),

    # --- SPECTRAL CHANNELS ---
    EncyclopediaEntry(
        key="sat_channel_visible",
        name="Canaux Satellitaires Visibles (VIS 0.6 µm / 0.8 µm)",
        domain="Satellites Météorologiques",
        subdomain="Canaux spectraux",
        equation="Réflectance du rayonnement solaire: Albedo = I_réfléchi / I_incident",
        latex_equation=r"\rho_{\text{vis}} = \frac{\pi L_{\lambda}}{\mu_0 F_0}",
        variables={"L_lambda": "Luminance mesurée", "F0": "Éclairement solaire au sommet d'atmosphère"},
        units={"Réflectance": "% / dimensionless"},
        description="Canaux mesurant le rayonnement solaire réfléchi par les nuages, la neige et le sol. Essentiels pour déterminer l'épaisseur optique des nuages et la texture fine des structures convectives.",
        application_conditions=["Observation de jour uniquement (angles zénithaux solaires < 85°)"],
        limitations=["Indisponible la nuit"],
        references=["EUMETSAT / NOAA Spectral Channel Guides"],
    ),
    EncyclopediaEntry(
        key="sat_channel_ir_window",
        name="Canal Infrarouge Thermique Fenêtre (IR 10.8 µm)",
        domain="Satellites Météorologiques",
        subdomain="Canaux spectraux",
        equation="Température de Brillance: BT = B^-1(I_10.8)",
        latex_equation=r"T_b = \frac{h c}{\lambda k_B \ln\left(1 + \frac{2 h c^2}{\lambda^5 I_\lambda}\right)}",
        variables={"I_lambda": "Radiance thermique infrarouge mesurée dans la fenêtre 10.5-12.5 µm"},
        units={"BT": "K / °C"},
        description="Canal infrarouge thermique mesurant l'émission propre de la surface ou des nuages sans être absorbé par la vapeur d'eau. Permet d'estimer la température du sommet des nuages jour et nuit.",
        application_conditions=["Observation 24h/24 des nuages et de la SST"],
        limitations=["Transparence partielle des cirrus fins nécessitant des corrections d'émissivité"],
        references=["EUMETSAT SEVIRI Channel Documentation", "NOAA NESDIS"],
    ),
    EncyclopediaEntry(
        key="sat_channel_water_vapor",
        name="Canal Vapeur d'Eau (WV 6.2 µm / 7.3 µm)",
        domain="Satellites Météorologiques",
        subdomain="Canaux spectraux",
        equation="Absorption par la bande de vibration-rotation de H2O",
        latex_equation=r"I_{\text{WV}} = \int B_\lambda(T(z)) \frac{\partial \tau_\lambda(z, z_{\text{sat}})}{\partial z} dz",
        variables={"tau": "Transmittance atmosphérique dépendant du contenu en vapeur d'eau"},
        units={"BT": "K"},
        description="Canal sensible à l'humidité de la moyenne et haute troposphère (300-600 hPa). Révèle les thalwegs, les jets-streams, les anomalies de tropopause et les ondes de gravité.",
        application_conditions=["Visualisation de la dynamique de haute troposphère même en l'absence de nuages"],
        limitations=["Ne voit pas les basses couches sous la couche d'absorption de vapeur d'eau"],
        references=["EUMETSAT / WMO Satellite Manuals", "SANTOS & SCHMETZ (1996)"],
    ),
    EncyclopediaEntry(
        key="sat_channel_co2_slicing",
        name="Canal d'Absorption CO2 (13.3 µm)",
        domain="Satellites Météorologiques",
        subdomain="Canaux spectraux",
        equation="Atténuation par la bande d'absorption de CO2 pour l'assignation en altitude",
        latex_equation=r"\frac{I(\lambda_1) - I_{\text{clr}}(\lambda_1)}{I(\lambda_2) - I_{\text{clr}}(\lambda_2)} = \frac{\epsilon_1 \int_{P_s}^{P_c} \tau_1 d B_1}{\epsilon_2 \int_{P_s}^{P_c} \tau_2 d B_2}",
        variables={"Pc": "Pression du sommet du nuage (hPa)", "epsilon": "Émissivité"},
        units={"Pression": "hPa"},
        description="Technique du CO2 slicing utilisant la bande à 13.3 µm pour déterminer avec haute précision l'altitude et la pression du sommet des nuages semi-transparents (cirrus).",
        application_conditions=["Restitution de la hauteur des nuages hauts dans les algorithmes NWP SAF"],
        limitations=["Sensibilité réduite pour les nuages très bas proches de la surface"],
        references=["Menzel et al. (1983) J. Climate Appl. Meteor.", "EUMETSAT NWP SAF"],
    ),

    # --- ALGORITHMS ---
    EncyclopediaEntry(
        key="cloud_mask_algorithm",
        name="Algorithme de Masque de Nuages (Cloud Mask)",
        domain="Satellites Météorologiques",
        subdomain="Algorithmes satellitaires",
        equation="Test multi-spectral de seuil et de cohérence spatiale: Pixel = Ciel Clair / Nuageux / Incertain",
        latex_equation=r"\text{Test: } R_{\text{vis}} > R_{\text{threshold}}(\phi, \theta) \quad \lor \quad BT_{10.8} < BT_{\text{surface}} - \Delta T",
        variables={"R_vis": "Réflectance visible", "BT": "Température de brillance IR"},
        units={"Flag": "Clair (0) / Nuage (1)"},
        description="Première étape fondamentale du traitement d'images satellitaires séparant les pixels de ciel clair des pixels ennuagés par des tests de réflectance et de température.",
        application_conditions=["Prétraitement obligatoire pour toutes les restitutions physiques satellitaires"],
        limitations=["Difficultés sur les surfaces enneigées/glacées (albedo similaire aux nuages)"],
        references=["Derrien & Le Gléau (2005) Int. J. Remote Sens. (NMA SAF)", "NOAA Enterprise Cloud Mask"],
    ),
    EncyclopediaEntry(
        key="cloud_top_temperature_retrieval",
        name="Restitution de la Température du Sommet des Nuages (CTT / CTH)",
        domain="Satellites Météorologiques",
        subdomain="Algorithmes satellitaires",
        equation="CTT = B_inv(BT_10.8) pour les nuages opaques",
        latex_equation=r"T_{\text{top}} = B_{10.8}^{-1}(I_{10.8}), \quad z_{\text{top}} = \text{Sounding}^{-1}(T_{\text{top}})",
        variables={"CTT": "Cloud Top Temperature (K)", "CTH": "Cloud Top Height (m)"},
        units={"CTT": "K / °C", "CTH": "m"},
        description="Algorithme estimant la température et l'altitude du sommet des couches nuageuses en croisant la température de brillance IR avec un profil de température NWP.",
        application_conditions=["Nowcasting, sécurité aviation et assimilation satellitaire"],
        limitations=["Correction d'émissivité requise pour les cirrus fins semi-transparents"],
        references=["EUMETSAT NWC SAF Documentation", "NOAA NESDIS Satellite Products"],
    ),
    EncyclopediaEntry(
        key="cloud_optical_thickness_cot",
        name="Épaisseur Optique et Rayon Effectif des Nuages (COT & CER)",
        domain="Satellites Météorologiques",
        subdomain="Algorithmes satellitaires",
        equation="Méthode Bi-spectrale de Nakajima & King (VIS 0.6µm & SWIR 2.1µm)",
        latex_equation=r"\tau_{\text{cloud}} = f(R_{0.6\mu m}, r_e), \quad r_e = g(R_{2.1\mu m}, \tau_{\text{cloud}})",
        variables={"tau_cloud": "Épaisseur optique nuageuse COT", "re": "Rayon effectif des gouttelettes CER (µm)"},
        units={"COT": "dimensionless", "CER": "µm"},
        description="Restitution simultanée de l'épaisseur optique intégrée du nuage et de la taille moyenne des gouttelettes/cristaux au sommet du nuage.",
        application_conditions=["Caractérisation microphysique satellitaire"],
        limitations=["Valide uniquement de jour sous éclairement solaire direct"],
        references=["Nakajima & King (1990) J. Atmos. Sci.", "NASA MODIS Cloud Product ATBD"],
    ),
]

for entry in ENTRIES:
    EncyclopediaRegistry.register(entry)
