"""
Atmospheric Complexity Framework (ACF)

NWP Cloud Microphysics Schemes Encyclopedia Module (WRF, AROME, ECMWF IFS, ICON)
"""

from typing import Any

from acf.science.encyclopedia.entry import EncyclopediaEntry
from acf.science.encyclopedia.registry import EncyclopediaRegistry

SCHEMES: list[dict[str, Any]] = [
    # --- WRF SCHEMES ---
    {
        "key": "wrf_thompson_scheme",
        "name": "Schéma Microphysique de Thompson (WRF)",
        "domain": "Nuages & Microphysique",
        "subdomain": "Schémas NWP WRF",
        "equation": "Prognostic: qc, qr, qi, qs, qg, Nr, Ni (2-moment pour pluie et glace)",
        "latex_equation": r"\frac{\partial (\rho q_x)}{\partial t} = \text{ADV} + \text{DIF} + S_{\text{Thompson}}, \quad N(D) = N_0 D^\mu e^{-\lambda D}",
        "variables": {"q_x": "qc, qr, qi, qs, qg (kg/kg)", "N_r, N_i": "Concentrations numériques (m⁻³)"},
        "units": {"q_x": "kg/kg", "N_x": "m⁻³"},
        "description": "Schéma microphysique hybride 1-moment / 2-moments développé par NCAR. Utilise une distribution en taille variable pour la neige et modélise la germination de la glace en fonction des aérosols.",
        "application_conditions": ["Prévision numérique à haute résolution (WRF-ARW, 1-3 km)"],
        "limitations": ["Coût computationnel modéré à élevé"],
        "references": ["Thompson et al. (2008) Mon. Wea. Rev.", "NCAR WRF Technical Note"],
    },
    {
        "key": "wrf_morrison_scheme",
        "name": "Schéma Microphysique de Morrison 2-Moments (WRF)",
        "domain": "Nuages & Microphysique",
        "subdomain": "Schémas NWP WRF",
        "equation": "Prognostic: qc, qr, qi, qs, qg et concentrations N_r, N_i, N_s, N_g",
        "latex_equation": r"\frac{\partial N_x}{\partial t} = -\nabla \cdot (\mathbf{u} N_x) + S_{N,x}, \quad \frac{\partial q_x}{\partial t} = -\nabla \cdot (\mathbf{u} q_x) + S_{q,x}",
        "variables": {"q_x": "Masse d'hydrométéores (kg/kg)", "N_x": "Nombre de particules par unité de volume (m⁻³)"},
        "units": {"q_x": "kg/kg", "N_x": "m⁻³"},
        "description": "Schéma à 2 moments prédisant simultanément la masse et le nombre pour 4 espèces précipitantes, permettant un traitement précis des distributions de taille.",
        "application_conditions": ["Simulations méso-échelle et convection explicite"],
        "limitations": ["Augmentation du nombre de variables pronostiques transportées"],
        "references": ["Morrison et al. (2009) Mon. Wea. Rev.", "AMS Microphysics Documentation"],
    },
    {
        "key": "wrf_wdm6_scheme",
        "name": "Schéma WDM6 (WRF Double-Moment 6-Class)",
        "domain": "Nuages & Microphysique",
        "subdomain": "Schémas NWP WRF",
        "equation": "Prognostic: qc, qr, qi, qs, qg, qh + N_c, N_r et CCN",
        "latex_equation": r"\frac{\partial N_{ccn}}{\partial t} = -\nabla \cdot (\mathbf{u} N_{ccn}) + S_{ccn}",
        "variables": {
            "6 hydrométéores": "qc, qr, qi, qs, qg, qh",
            "N_c, N_r": "Nombre gouttelettes & pluie",
            "N_ccn": "Noyaux de condensation (m⁻³)",
        },
        "units": {"q": "kg/kg", "N": "m⁻³"},
        "description": "Extension à double moment du schéma WSM6 incluant la prédiction explicite des noyaux de condensation (CCN) et des concentrations de gouttelettes d'eau nuageuse.",
        "application_conditions": ["Études d'interactions aérosols-nuages et précipitations intenses"],
        "limitations": ["Sensible aux profils initiaux de CCN"],
        "references": ["Lim & Hong (2010) Mon. Wea. Rev.", "NCAR WRF User Guide"],
    },
    {
        "key": "wrf_lin_scheme",
        "name": "Schéma Microphysique de Lin-Farley-Orville (WRF)",
        "domain": "Nuages & Microphysique",
        "subdomain": "Schémas NWP WRF",
        "equation": "Prognostic: qc, qr, qi, qs, qg (5 espèces à 1 moment)",
        "latex_equation": r"\frac{\partial q_x}{\partial t} = \text{ADV}(q_x) + \text{DIF}(q_x) + P_{\text{Lin}}",
        "variables": {"5 espèces": "Eau nuageuse, pluie, glace, neige, graupel"},
        "units": {"q": "kg/kg"},
        "description": "Schéma classique à 1 moment pionnier des modèles méso-échelle, robuste et efficace pour la convection convective profonde.",
        "application_conditions": ["Prévision convective classique à résolution moyenne"],
        "limitations": ["Distribution des tailles supposée fixe (N0 fixe)"],
        "references": ["Lin, Farley & Orville (1983) J. Climate Appl. Meteor.", "NOAA / NCEP Documentation"],
    },
    {
        "key": "wrf_goddard_scheme",
        "name": "Schéma Microphysique Goddard (NASA / WRF)",
        "domain": "Nuages & Microphysique",
        "subdomain": "Schémas NWP NASA",
        "equation": "Prognostic: qc, qr, qi, qs, qg (ou qh) avec équilibre thermique de la glace",
        "latex_equation": r"\frac{\partial q_x}{\partial t} = S_{\text{Goddard}}(qc, qr, qi, qs, qg)",
        "variables": {"Hydrométéores": "qc, qr, qi, qs, qg"},
        "units": {"q": "kg/kg"},
        "description": "Schéma à 3 espèces de glace développé par la NASA (Goddard Space Flight Center), optimisé pour les simulations de cyclones tropicaux et la validation radar/satellite (TRMM/GPM).",
        "application_conditions": ["Convection tropicale, simulations de systèmes convectifs"],
        "limitations": ["Paramétrisation 1-moment de base"],
        "references": ["Tao et al. (2003) Meteorol. Atmos. Phys.", "NASA GSFC Microphysics ATBD"],
    },
    # --- AROME / METEO-FRANCE SCHEMES ---
    {
        "key": "arome_ice3_scheme",
        "name": "Schéma Microphysique ICE3 (Météo-France / AROME)",
        "domain": "Nuages & Microphysique",
        "subdomain": "Schémas NWP AROME",
        "equation": "Prognostic: qc, qr, qi, qs, qg (5 hydrométéores à 1 moment)",
        "latex_equation": r"\frac{\partial (\rho q_x)}{\partial t} = \text{ADV} + \text{DIF} + S_{\text{ICE3}}",
        "variables": {"qc": "Eau nuageuse", "qr": "Pluie", "qi": "Glace nuageuse", "qs": "Neige", "qg": "Graupel"},
        "units": {"q": "kg/kg"},
        "description": "Schéma microphysique opérationnel d'AROME pour la modélisation à haute résolution (1.3 km) des nuages et précipitations.",
        "application_conditions": ["Prévision numérique du temps à haute résolution (AROME, ALADIN)"],
        "limitations": ["Grêle non explicitée séparément du graupel (traité dans ICE4)"],
        "references": ["Pinty & Jabouille (1998)", "Météo-France AROME Documentation"],
    },
    {
        "key": "arome_ice4_scheme",
        "name": "Schéma Microphysique ICE4 (Météo-France / Meso-NH)",
        "domain": "Nuages & Microphysique",
        "subdomain": "Schémas NWP AROME",
        "equation": "Prognostic: qc, qr, qi, qs, qg, qh (6 hydrométéores avec grêle explicite qh)",
        "latex_equation": r"\frac{\partial (\rho q_h)}{\partial t} = S_{\text{hail\_riming}} + S_{\text{hail\_wet\_growth}} - S_{\text{hail\_melt}}",
        "variables": {"qh": "Rapport de mélange de la grêle (kg/kg)"},
        "units": {"q": "kg/kg"},
        "description": "Extension à 6 espèces d'ICE3 introduisant la catégorie grêle (qh) et la croissance humide (wet growth) pour la prévision des orages violents.",
        "application_conditions": ["Prévision des orages supercellulaires et risque de grêle au sol"],
        "limitations": ["Coût de calcul supplémentaire de ~20%"],
        "references": ["Lascaux et al. (2006)", "Meso-NH / AROME Scientific Manual"],
    },
    {
        "key": "mesonh_lima_scheme",
        "name": "Schéma Microphysique LIMA (Meso-NH / Météo-France)",
        "domain": "Nuages & Microphysique",
        "subdomain": "Schémas NWP Meso-NH",
        "equation": "Prognostic: Masse q_x et Nombre N_x pour nuage, pluie, glace et aérosols (AP)",
        "latex_equation": r"\frac{\partial N_{ap}}{\partial t} = \text{ADV}(N_{ap}) + S_{\text{act}} + S_{\text{dep}}",
        "variables": {"q_x, N_x": "Masses et concentrations", "N_ap": "Population d'aérosols activables (CCN & IN)"},
        "units": {"q": "kg/kg", "N": "m⁻³"},
        "description": "Schéma microphysique quasi-2-moments pronostiquant explicitement les populations d'aérosols (noyaux de condensation et noyaux glaçogènes) et leur interaction avec la microphysique.",
        "application_conditions": ["Simulations de recherche haute fidélité aérosol-nuage"],
        "limitations": ["Très coûteux en mémoire et temps GPU/CPU"],
        "references": ["Vié et al. (2016) Geosci. Model Dev.", "CNRM / Météo-France"],
    },
    # --- ECMWF IFS SCHEMES ---
    {
        "key": "ecmwf_ifs_cloud_scheme",
        "name": "Schéma de Nuages Pronostiques de l'ECMWF IFS",
        "domain": "Nuages & Microphysique",
        "subdomain": "Schémas NWP ECMWF",
        "equation": "Prognostic: Fraction nuageuse a, q_l, q_i, q_r, q_s (Tiedtke-Forbes)",
        "latex_equation": r"\frac{\partial a}{\partial t} = A(a) + S_{\text{form}} - S_{\text{evap}}, \quad \frac{\partial q_l}{\partial t} = A(q_l) + S_{\text{cond}} - S_{\text{auto}}",
        "variables": {
            "a": "Fraction couvrant la grille (0 à 1)",
            "ql, qi": "Eau et glace nuageuses",
            "qr, qs": "Pluie et neige pronostiques",
        },
        "units": {"a": "dimensionless", "q": "kg/kg"},
        "description": "Schéma pronostique de fraction nuageuse et d'hydrométéores (Tiedtke 1993, Forbes et al. 2011) utilisé dans le modèle global de l'ECMWF.",
        "application_conditions": ["Prévision numérique globale à l'échelle du globe (ECMWF IFS)"],
        "limitations": ["Représentation sous-maille pour les résolutions > 9 km"],
        "references": ["Tiedtke (1993) Mon. Wea. Rev.", "Forbes et al. (2011) ECMWF Tech Memo"],
    },
    {
        "key": "ecmwf_ifs_ice_processes",
        "name": "Processus Glacés du Modèle ECMWF IFS",
        "domain": "Nuages & Microphysique",
        "subdomain": "Schémas NWP ECMWF",
        "equation": "Prognostic: Germination, Déposition, Agrégation et Sédimentation de la glace",
        "latex_equation": r"\frac{\partial q_i}{\partial t} = S_{\text{nuc}} + S_{\text{dep}} - S_{\text{agg}} - \frac{1}{\rho}\frac{\partial (\rho V_i q_i)}{\partial z}",
        "variables": {"qi": "Rapport de mélange de la glace", "Vi": "Vitesse de chute de la glace (m/s)"},
        "units": {"q": "kg/kg", "V": "m/s"},
        "description": "Paramétrisation des processus de phase froide (germination homogène/hétérogène, croissance par déposition, agrégation) dans l'ECMWF IFS.",
        "application_conditions": ["Troposphère supérieure et zones polaires globales"],
        "limitations": ["Dépendance à la fonction d'émissivité des cirrus"],
        "references": ["ECMWF IFS Documentation Part IV: Physical Processes", "WMO NWP Docs"],
    },
    # --- ICON SCHEME ---
    {
        "key": "icon_seifert_beheng",
        "name": "Schéma Microphysique à 2-Moments Seifert-Beheng (DWD / ICON)",
        "domain": "Nuages & Microphysique",
        "subdomain": "Schémas NWP ICON",
        "equation": "Prognostic: Mass (q_x) & Number (N_x) for 6 hydrometeor classes (qc, qr, qi, qs, qg, qh)",
        "latex_equation": r"\frac{\partial N_x}{\partial t} + \nabla \cdot (\mathbf{u} N_x) = S_{N,x}, \quad \frac{\partial q_x}{\partial t} + \nabla \cdot (\mathbf{u} q_x) = S_{q,x}",
        "variables": {
            "6 espèces": "Gouttelettes, Pluie, Glace, Neige, Graupel, Grêle",
            "N_x": "Concentrations numériques (m⁻³)",
        },
        "units": {"q": "kg/kg", "N": "m⁻³"},
        "description": "Schéma microphysique à 2 moments avancé utilisé dans le modèle ICON du DWD (Deutscher Wetterdienst) prédisant la masse et le nombre de 6 catégories d'hydrométéores.",
        "application_conditions": ["Modèle ICON à grille icosaédrique (résolutions globales et régionales)"],
        "limitations": ["Nombre élevé de variables de transport (12 champs 3D)"],
        "references": ["Seifert & Beheng (2006) Meteorol. Atmos. Phys.", "DWD ICON Model Documentation"],
    },
]

for s in SCHEMES:
    entry = EncyclopediaEntry(
        key=s["key"],
        name=s["name"],
        domain=s["domain"],
        subdomain=s["subdomain"],
        equation=s["equation"],
        latex_equation=s["latex_equation"],
        variables=s.get("variables", {}),
        units=s.get("units", {}),
        description=s["description"],
        application_conditions=s.get("application_conditions", []),
        limitations=s.get("limitations", []),
        references=s["references"],
    )
    EncyclopediaRegistry.register(entry)
