"""
Operational NWP Physics & Parameterization Schemes Encyclopedia Module
"""

from acf.science.encyclopedia.entry import EncyclopediaEntry
from acf.science.encyclopedia.registry import EncyclopediaRegistry

ENTRIES: list[EncyclopediaEntry] = [
    EncyclopediaEntry(
        key="thompson_microphysics_scheme",
        name="Schéma Microphysique Aerosol-Aware de Thompson",
        domain="Paramétrisations Physiques NWP",
        subdomain="Microphysique des nuages",
        equation="Prédiction à 2 moments de la masse et du nombre de gouttes/glace en fonction des aérosols",
        latex_equation=r"\frac{\partial q_x}{\partial t} = \text{Physique}(q_x, N_x, \text{CCN}, \text{INP})",
        variables={
            "qx": "Rapport de mélange (qc, qi, qr, qs, qg)",
            "Nx": "Concentration numérique (Nc, Ni, Nr, Ns, Ng)",
            "CCN/INP": "Aérosols activés",
        },
        units={"qx": "kg/kg", "Nx": "m⁻³"},
        description="Schéma microphysique à 2 moments ultra-performant prédisant l'eau nuageuse, la glace, la pluie, la neige et le graupel avec prise en compte explicite du nombre d'aérosols CCN et INP.",
        application_conditions=["Modèles NWP méso-échelle à haute résolution (WRF-ARW, NOAA HRRR)"],
        limitations=["Sensible aux profils verticaux d'aérosols prescrits ou assimilés"],
        references=["Thompson et al. (2008) Mon. Wea. Rev.", "Thompson & Eidhammer (2014) J. Atmos. Sci."],
    ),
    EncyclopediaEntry(
        key="morrison_two_moment_microphysics",
        name="Schéma Microphysique à 2 Moments de Morrison",
        domain="Paramétrisations Physiques NWP",
        subdomain="Microphysique des nuages",
        equation="Prédiction simultanée de (q_r, N_r, q_i, N_i, q_s, N_s, q_g, N_g)",
        latex_equation=r"\frac{\partial q_x}{\partial t} = \text{Sources} - \text{Puits}, \quad \frac{\partial N_x}{\partial t} = \text{Sources}_N - \text{Puits}_N",
        variables={
            "qx": "Rapports de mélange des 5 espèces d'hydrométéores",
            "Nx": "Concentrations numériques des 5 espèces",
        },
        units={"qx": "kg/kg", "Nx": "m⁻³"},
        description="Schéma microphysique complet prédisant la masse et la concentration numérique pour 4 ou 5 catégories d'hydrométéores. Largement utilisé pour la prévision des orages et supercellules.",
        application_conditions=["Simulations convectives et modèles NWP à méso-échelle"],
        limitations=["Coût en mémoire et temps de calcul doublé par rapport aux schémas à 1 moment"],
        references=["Morrison et al. (2005) Mon. Wea. Rev.", "Morrison et al. (2009) Mon. Wea. Rev."],
    ),
    EncyclopediaEntry(
        key="rrtmg_radiation_scheme",
        name="Schéma Radiatif RRTMG (Rapid Radiative Transfer Model)",
        domain="Paramétrisations Physiques NWP",
        subdomain="Transfert radiatif",
        equation="Méthode Correlated-k avec 16 bandes SW et 14 bandes LW pour le transfert radiatif",
        latex_equation=r"F_{\text{net}}(z) = F_{\text{SW}}^\downarrow(z) - F_{\text{SW}}^\uparrow(z) + F_{\text{LW}}^\downarrow(z) - F_{\text{LW}}^\uparrow(z)",
        variables={
            "SW": "16 bandes spectrales ondes courtes (0.2 à 12.2 µm)",
            "LW": "14 bandes spectrales infrarouge long (3.0 à 1000 µm)",
        },
        units={"Flux": "W/m²"},
        description="Schéma de transfert radiatif standard international développé à l'AER (Atmospheric and Environmental Research) modélisant l'absorption/diffusion par H2O, O3, CO2, CH4, N2O, les nuages et les aérosols.",
        application_conditions=["Modèles NWP globaux et régionaux (WRF, GFS, CESM)"],
        limitations=["Appel coûteux généralement effectué toutes les 15 à 30 minutes de temps simulé"],
        references=["Mlawer et al. (1997) J. Geophys. Res.", "Iacono et al. (2008) J. Geophys. Res."],
    ),
    EncyclopediaEntry(
        key="ysu_pbl_scheme",
        name="Schéma de Couche Limite de Yonsei University (YSU PBL)",
        domain="Paramétrisations Physiques NWP",
        subdomain="Couche limite & Turbulence",
        equation="Profil K-profile non-local avec terme de transport contre-gradient et entraînement au sommet",
        latex_equation=r"\frac{\partial C}{\partial t} = \frac{\partial}{\partial z} \left[ K_c \left( \frac{\partial C}{\partial z} - \gamma_c \right) \right] + h_{\text{entrainement}}",
        variables={
            "Kc": "Coefficient de diffusion turbulente vertical",
            "gamma_c": "Terme de transport non-local contre-gradient",
        },
        units={"Kc": "m²/s"},
        description="Schéma de couche limite planétaire non-local de première génération amélioré incluant une représentation explicite des flux d'entraînement au sommet de la PBL.",
        application_conditions=["Convection thermique diurne et mélange turbulent fort"],
        limitations=["Peut surestimer l'épaisseur de la couche limite en conditions très instables"],
        references=["Hong et al. (2006) Mon. Wea. Rev.", "Noh et al. (2003) Boundary-Layer Meteorol."],
    ),
    EncyclopediaEntry(
        key="surfex_land_surface_model",
        name="Plate-forme de Modélisation de Surface SURFEX (Météo-France)",
        domain="Paramétrisations Physiques NWP",
        subdomain="Modèles de surface",
        equation="Couplage multi-surface: ISBA (Végétation/Sol), TEB (Villes), FLake (Lacs), GELATO (Mer/Glace)",
        latex_equation=r"R_n = H + LE + G + \Delta S",
        variables={
            "ISBA": "Interaction Soil-Biosphere-Atmosphere",
            "TEB": "Town Energy Balance",
            "FLake": "Freshwater Lake Model",
        },
        units={"Flux": "W/m²"},
        description="Système complet d'intégration des échanges d'énergie, de masse et d'impulsion entre la surface terrestre et l'atmosphère utilisé dans AROME, ARPEGE, HARMONIE et le modèle du climat CNRM-CM.",
        application_conditions=["Modèles de prévision numérique Météo-France et consortium ACCORD"],
        limitations=["Complexité d'initialisation des bases de données d'occupation du sol (ECOCLIMAP)"],
        references=["Masson et al. (2013) Geosci. Model Dev.", "Noilhan & Planton (1989) Mon. Wea. Rev."],
    ),
    EncyclopediaEntry(
        key="kain_fritsch_convection_scheme",
        name="Schéma Convectif de Mass-Flux de Kain-Fritsch",
        domain="Paramétrisations Physiques NWP",
        subdomain="Convection profonde et peu profonde",
        equation="Modèle de panache convective à entraînement/détraînement avec fermeture par consommation du CAPE",
        latex_equation=r"\tau_{\text{adj}} \approx 30\text{--}60 \text{ min}, \quad M_u(z) = M_u(z_b) + \int (E - D) dz",
        variables={
            "Mu": "Flux de masse ascendant",
            "E": "Taux d'entraînement",
            "D": "Taux de détraînement",
            "tau_adj": "Temps de relaxation de la fermeture CAPE",
        },
        units={"Mu": "kg/(m²·s)"},
        description="Paramétrisation sous-maille de la convection profonde et peu profonde réajustant les profils de température et d'humidité en éliminant le CAPE sur une échelle de temps de 30 à 60 minutes.",
        application_conditions=["Modèles NWP à résolution intermédiaire (dx = 5 à 25 km)"],
        limitations=["Doit être désactivé dans les modèles résolvant la convection (dx < 3 km)"],
        references=["Kain & Fritsch (1990) J. Atmos. Sci.", "Kain (2004) J. Appl. Meteor."],
    ),
    EncyclopediaEntry(
        key="teb_urban_canopy_model",
        name="Modèle de Canopée Urbaine TEB (Town Energy Balance)",
        domain="Paramétrisations Physiques NWP",
        subdomain="Schémas urbains",
        equation="Bilan d'énergie à 3 géométries: Toits, Murs et Rues (Canyons urbains)",
        latex_equation=r"Q^* + Q_F = H_{\text{town}} + LE_{\text{town}} + G_{\text{town}}",
        variables={
            "QF": "Chaleur anthropique (trafic, chauffage, climatisation)",
            "H_town": "Flux de chaleur sensible urbain",
        },
        units={"Flux": "W/m²"},
        description="Premier schéma physique de surface décrivant les transferts micro-climatiques en milieu urbain par géométrie de canyon tridimensionnelle. Prédit les îlots de chaleur urbains (ICU).",
        application_conditions=["Prévision numérique haute résolution des villes et îlots de chaleur (AROME, SURFEX)"],
        limitations=["Suppose des canyons urbains isotropes infiniment longs"],
        references=["Masson (2000) Boundary-Layer Meteorol.", "Pigeon et al. (2008) J. Appl. Meteor. Climatol."],
    ),
    EncyclopediaEntry(
        key="flake_lake_model",
        name="Modèle de Lac à Deux Couches FLake (Freshwater Lake Model)",
        domain="Paramétrisations Physiques NWP",
        subdomain="Modèles de lacs",
        equation="Profil de température paramétré avec couche de mélange supérieure et thermocline",
        latex_equation=r"\frac{T(z,t) - T_s(t)}{\Delta T(t)} = \Phi\left(\frac{z - h(t)}{D - h(t)}\right)",
        variables={
            "Ts": "Température de surface du lac",
            "h": "Profondeur de la couche de mélange",
            "Phi": "Fonction universelle de forme de thermocline",
        },
        units={"Ts": "K", "h": "m"},
        description="Modèle d'eau douce à deux couches fondé sur le concept d'auto-similitude du profil thermique de la thermocline. Prévoit la température de surface de l'eau, la prise en glace et la fonte des lacs.",
        application_conditions=["Intégration des lacs dans les modèles NWP (DWD ICON, COSMO, AROME, ECMWF IFS)"],
        limitations=["Conçu pour les lacs de profondeur moyenne à faible (< 50 m)"],
        references=["Mironov (2008) DWD Work Report", "Mironov et al. (2010) Boreal Env. Res."],
    ),
]

for entry in ENTRIES:
    EncyclopediaRegistry.register(entry)
