"""
Atmospheric Physics Laws
"""

from acf.science.laws.base_law import AtmosphericLaw

ATMOSPHERIC_LAWS = [
    AtmosphericLaw(
        key="hydrostatic_equilibrium",
        name="Équilibre Hydrostatique",
        domain="Physique Atmosphérique",
        equation="dp/dz = -rho * g",
        variables={
            "p": "Pression atmosphérique",
            "z": "Altitude",
            "rho": "Masse volumique de l'air",
            "g": "Accélération de la pesanteur (9.81 m/s²)",
        },
        units={"p": "Pa", "z": "m", "rho": "kg/m³", "g": "m/s²"},
        description="Loi fondamentale décrivant l'équilibre vertical entre la force du gradient de pression et la gravité.",
        references=[
            "WMO-No. 8: Guide to Meteorological Instruments and Methods of Observation",
            "Holton, J. R., & Hakim, G. J. (2012). An Introduction to Dynamic Meteorology.",
        ],
        limitations=[
            "Valable pour les échelles synoptiques et méso-échelles.",
            "Néglige l'accélération verticale dw/dt (non hydrostatique).",
        ],
        compute_func=lambda density, gravity=9.81, dz=1.0: -density * gravity * dz,
    ),
    AtmosphericLaw(
        key="ideal_gas_law",
        name="Équation d'État du Gaz Parfait",
        domain="Physique Atmosphérique",
        equation="p = rho * Rd * T",
        variables={
            "p": "Pression atmosphérique",
            "rho": "Masse volumique de l'air sec",
            "Rd": "Constante spécifique de l'air sec (287.058 J/(kg·K))",
            "T": "Température absolue",
        },
        units={"p": "Pa", "rho": "kg/m³", "Rd": "J/(kg·K)", "T": "K"},
        description="Relie la pression, la masse volumique et la température de l'air sec.",
        references=["NOAA Technical Report NWS 28", "WMO Meteorological Glossary"],
        limitations=["Présuppose un comportement de gaz parfait à pression atmosphérique standard."],
        compute_func=lambda density, temperature, Rd=287.058: density * Rd * temperature,
    ),
    AtmosphericLaw(
        key="virtual_temperature",
        name="Température Virtuelle",
        domain="Physique Atmosphérique",
        equation="Tv = T * (1 + 0.61 * q)",
        variables={
            "T": "Température de l'air",
            "q": "Humidité spécifique",
            "Tv": "Température virtuelle",
        },
        units={"T": "K", "q": "kg/kg", "Tv": "K"},
        description="Température qu'aurait l'air sec pour avoir la même masse volumique que l'air humide à même pression.",
        references=["ECMWF IFS Documentation - Physical Processes"],
        limitations=["Valable pour les mélanges d'air avec de faibles fractions massiques de vapeur d'eau."],
        compute_func=lambda temperature, specific_humidity: temperature * (1.0 + 0.608 * specific_humidity),
    ),
    AtmosphericLaw(
        key="potential_temperature",
        name="Température Potentielle",
        domain="Physique Atmosphérique",
        equation="theta = T * (p0 / p) ** (Rd / cp)",
        variables={
            "T": "Température absolue",
            "p": "Pression mesurée",
            "p0": "Pression de référence (1000 hPa)",
            "kappa": "Rd/cp (~0.286)",
        },
        units={"T": "K", "p": "hPa", "theta": "K"},
        description="Température qu'aurait une parcelle d'air si elle était amenée adiabatiquement à 1000 hPa.",
        references=["Holton & Hakim (2012)", "WMO Technical Note"],
        limitations=["Processus adiabatique sans changement de phase de l'eau."],
        compute_func=lambda temperature, pressure, p0=1000.0, kappa=0.286: temperature * (p0 / pressure) ** kappa,
    ),
    AtmosphericLaw(
        key="primitive_equations",
        name="Équations Primitives Atmosphériques",
        domain="Physique Atmosphérique",
        equation="System of 5 non-linear PDEs (Navier-Stokes, Continuity, Thermodynamics)",
        variables={
            "u, v, w": "Composantes du vent",
            "T": "Température",
            "p": "Pression",
            "rho": "Masse volumique",
        },
        units={"u, v, w": "m/s", "T": "K", "p": "Pa", "rho": "kg/m³"},
        description="Ensemble fondamental d'équations régissant la dynamique et la thermodynamique de l'atmosphère.",
        references=["ECMWF IFS Model Documentation", "NOAA NCEP GFS Manual"],
        limitations=["Résolution numérique nécessitant des discrétisations spatiales et temporelles."],
    ),
    AtmosphericLaw(
        key="mass_conservation",
        name="Conservation de la Masse (Équation de Continuité)",
        domain="Physique Atmosphérique",
        equation="d(rho)/dt + div(rho * V) = 0",
        variables={"rho": "Masse volumique", "V": "Vecteur vitesse (u, v, w)"},
        units={"rho": "kg/m³", "V": "m/s"},
        description="Exprime le principe de conservation de la masse dans un milieu continu fluide.",
        references=["NASA SP-8000 Series", "WMO Aerodynamics and Meteorology Manual"],
        limitations=["Considère l'atmosphère comme un fluide continu."],
    ),
    AtmosphericLaw(
        key="momentum_conservation",
        name="Conservation de la Quantité de Mouvement (Navier-Stokes Atmosphérique)",
        domain="Physique Atmosphérique",
        equation="DV/Dt = -1/rho * grad(p) - g*k - 2*Omega x V + F",
        variables={"V": "Vitesse", "p": "Pression", "Omega": "Vecteur rotation terrestre", "F": "Friction"},
        units={"V": "m/s", "p": "Pa", "Omega": "rad/s", "F": "m/s²"},
        description="Bilan des forces appliquées à une parcelle d'air (gradient de pression, gravité, Coriolis, frottement).",
        references=["Holton & Hakim (2012)", "ECMWF Scientific Reports"],
        limitations=["Nécessite la paramétrisation des sous-mailles et des forces de frottement."],
    ),
]
