"""
Atmospheric Complexity Framework (ACF)

EUMETSAT Data Store connector - real, live MTG (Météosat Troisième
Génération / FCI instrument) full-disk imagery.

Explicit user request: "je veux que toutes les maps affiché soient des
maps du mtg" (all maps should show MTG imagery), scoped to the map
BASEMAP (acf.gui.map.mtg_basemap) across every real map view (ESOC's
main map, the AWCI dashboard, the Classic Dashboard).

What this actually fetches, and why (read before assuming this decodes
raw radiances): a full radiometric MTG/FCI Level 1c pipeline - satpy,
downloading and geolocating the ~40 rapid-scan chunks a full-disk repeat
cycle is split into per band, building a true-color/natural-color RGB
composite - is a multi-day engineering effort on its own and was not
attempted here. Instead, this calls the SAME EUMETSAT Data Store this
project's user chose ("EUMETSAT Data Store (API officielle)", not the
public WMS/tile alternative) and uses that Store's own official "browse"
(Quicklook) asset, generated by EUMETSAT itself for every real product
in the collection - genuine, current MTG imagery on the FCI's own
~10-minute repeat cycle, not a placeholder or a fabricated pattern. The
honest limitation is resolution (a few hundred pixels across, a
thumbnail) and geolocation precision (no per-pixel geolocation grid ships
with the browse asset, so acf.gui.map.mtg_basemap places it using the
standard MTG-I1 geostationary viewing geometry rather than a grid read
from the product) - not the data being fake.

Collection IDs below were confirmed live against EUMETSAT's own
collection browse API (https://api.eumetsat.int/data/browse/collections,
queried directly while building this), not guessed from memory or
documentation that could be stale.
"""

from __future__ import annotations

import logging
import os
import time
from dataclasses import dataclass, field
from pathlib import Path
from typing import Any

import requests

try:
    from dotenv import load_dotenv
except ImportError:  # pragma: no cover - python-dotenv is an optional
    # "satellite" extra (pyproject.toml); .env is a convenience, not a
    # hard requirement - EUMETSAT_CONSUMER_KEY/SECRET can also come from
    # real process environment variables with no .env file at all.
    def load_dotenv(*_args: Any, **_kwargs: Any) -> bool:  # type: ignore[misc]
        return False


logger = logging.getLogger("acf.connectors.eumetsat_mtg")

TOKEN_URL = "https://api.eumetsat.int/token"
SEARCH_URL = "https://api.eumetsat.int/data/search-products/os"

#: FCI Level 1c Normal Resolution Image Data - MTG - 0 degree.
MTG_FCI_NORMAL_RESOLUTION = "EO:EUM:DAT:0662"
#: FCI Level 1c High Resolution Image Data - MTG - 0 degree (same
#: product family, heavier download, no benefit for a small basemap
#: thumbnail - not used by default).
MTG_FCI_HIGH_RESOLUTION = "EO:EUM:DAT:0665"

#: MTG-I1's real operational sub-satellite point and orbital altitude
#: (WGS84 mean geostationary altitude) - used by acf.gui.map.mtg_basemap
#: to place the fetched quicklook in a real Cartopy Geostationary CRS.
MTG_SUBSATELLITE_LONGITUDE_DEG = 0.0
MTG_SATELLITE_HEIGHT_M = 35_786_400.0


@dataclass
class MTGFetchResult:
    """Outcome of one fetch_latest_image() call - always honest about
    whether real image bytes came back, never a fabricated placeholder."""

    is_real_data: bool
    status: str
    authenticated: bool
    image_bytes: bytes | None = None
    product_id: str | None = None
    collection: str | None = None
    observation_start: str | None = None
    observation_end: str | None = None
    source_url: str | None = None
    fetched_at: float = field(default_factory=time.time)

    def as_dict(self) -> dict[str, Any]:
        return {
            "is_real_data": self.is_real_data,
            "status": self.status,
            "authenticated": self.authenticated,
            "image_bytes": self.image_bytes,
            "product_id": self.product_id,
            "collection": self.collection,
            "observation_start": self.observation_start,
            "observation_end": self.observation_end,
            "source_url": self.source_url,
            "fetched_at": self.fetched_at,
        }


class EUMETSATMTGConnector:
    """Fetches the latest live MTG full-disk quicklook from the EUMETSAT
    Data Store's real OpenSearch + browse endpoints (api.eumetsat.int).

    NOTE: credentials are read from EUMETSAT_CONSUMER_KEY/
    EUMETSAT_CONSUMER_SECRET (process environment, optionally loaded from
    a local .env via python-dotenv - see .env.example) rather than
    config/eumetsat.yaml, which IS tracked in git - same "credentials
    never committed" rule the HPC Connection Wizard's password field
    already follows (see acf.gui.esoc.hpc_connection_dialog).
    """

    def __init__(
        self,
        collection: str = MTG_FCI_NORMAL_RESOLUTION,
        env_path: Path | str | None = None,
    ) -> None:
        # override=False: a real environment variable already set by the
        # caller's shell/process wins over anything in .env - .env is a
        # local-dev convenience, not meant to shadow deliberate env config.
        load_dotenv(dotenv_path=env_path, override=False)
        self.collection = collection
        self._consumer_key = os.environ.get("EUMETSAT_CONSUMER_KEY", "").strip()
        self._consumer_secret = os.environ.get("EUMETSAT_CONSUMER_SECRET", "").strip()
        self._access_token: str | None = None
        self._token_expires_at: float = 0.0

    @property
    def has_credentials(self) -> bool:
        return bool(self._consumer_key and self._consumer_secret)

    def _authenticate(self) -> str | None:
        """Real OAuth2 client_credentials exchange against
        api.eumetsat.int/token. Returns None (and logs why) rather than
        fabricating a token when credentials are missing or the exchange
        fails - callers fall back to an anonymous request, which the
        Data Store's search/browse endpoints currently still serve
        (confirmed live while building this), just without the higher
        rate-limit headroom an authenticated request gets.
        """
        if not self.has_credentials:
            return None
        if self._access_token and time.time() < self._token_expires_at - 30:
            return self._access_token
        try:
            resp = requests.post(
                TOKEN_URL,
                data={"grant_type": "client_credentials"},
                auth=(self._consumer_key, self._consumer_secret),
                timeout=15,
            )
            resp.raise_for_status()
            payload = resp.json()
            self._access_token = payload["access_token"]
            self._token_expires_at = time.time() + float(payload.get("expires_in", 3600))
            return self._access_token
        except Exception:
            logger.exception("EUMETSAT OAuth2 token request failed")
            self._access_token = None
            return None

    def fetch_latest_image(self) -> MTGFetchResult:
        """Return the latest real MTG full-disk quicklook, or an honest
        NOT_FETCHED_* status - never a fabricated placeholder image."""
        token = self._authenticate()
        headers = {"Authorization": f"Bearer {token}"} if token else {}

        try:
            search_resp = requests.get(
                SEARCH_URL,
                params={
                    "format": "json",
                    "pi": self.collection,
                    "si": 0,
                    "c": 1,
                    "sort": "start,time,0",
                },
                headers=headers,
                timeout=20,
            )
            search_resp.raise_for_status()
            features = search_resp.json().get("features", [])
        except Exception as exc:
            logger.exception("EUMETSAT Data Store search failed")
            return MTGFetchResult(
                is_real_data=False,
                status=f"NOT_FETCHED_SEARCH_FAILED: {exc}",
                authenticated=token is not None,
            )

        if not features:
            return MTGFetchResult(
                is_real_data=False,
                status="NOT_FETCHED_NO_PRODUCTS_RETURNED",
                authenticated=token is not None,
            )

        properties = features[0].get("properties", {})
        preview_links = properties.get("links", {}).get("previews", [])
        browse_url = next(
            (link["href"] for link in preview_links if link.get("title") == "Quicklook"),
            None,
        )
        if not browse_url:
            return MTGFetchResult(
                is_real_data=False,
                status="NOT_FETCHED_NO_QUICKLOOK_LINK",
                authenticated=token is not None,
            )

        try:
            image_resp = requests.get(browse_url, headers=headers, timeout=20)
            image_resp.raise_for_status()
        except Exception as exc:
            logger.exception("EUMETSAT quicklook download failed")
            return MTGFetchResult(
                is_real_data=False,
                status=f"NOT_FETCHED_DOWNLOAD_FAILED: {exc}",
                authenticated=token is not None,
            )

        start, _, end = properties.get("date", "").partition("/")
        return MTGFetchResult(
            is_real_data=True,
            status="FETCHED_OK",
            authenticated=token is not None,
            image_bytes=image_resp.content,
            product_id=properties.get("identifier"),
            collection=self.collection,
            observation_start=start or None,
            observation_end=end or None,
            source_url=browse_url,
        )
