"""
Atmospheric Complexity Framework (ACF)

HPC CONNECTOR - Resource Optimizer & Slurm Generator (ACF-HPC-004)

Estimates optimal compute resources (nodes, CPUs, memory, walltime, partition)
and generates optimized Slurm job submission scripts for NWP models.
"""

from __future__ import annotations

import math
from typing import Any


class HPCResourceOptimizer:
    """
    Slurm Resource Estimator and Script Generator.
    """

    @staticmethod
    def estimate_resources(model_name: str, config: dict[str, Any]) -> dict[str, Any]:
        """
        Estimates optimal node count, MPI tasks, memory, walltime, and partition.
        """
        model_upper = model_name.upper()
        grid_points = config.get("grid_points", 500000)
        forecast_hours = config.get("forecast_hours", 24)

        # Baseline scaling calculation
        if model_upper in ["AROME", "ALADIN"]:
            nodes = max(1, math.ceil((grid_points / 250000) * (forecast_hours / 24)))
            cpus_per_node = 32
            mem_per_node_gb = 128
            walltime_min = int(30 + (forecast_hours * 1.5))
            partition = "Researches"
        elif model_upper in ["ARPEGE", "IFS", "OPENIFS"]:
            nodes = max(2, math.ceil((grid_points / 100000) * (forecast_hours / 24)))
            cpus_per_node = 64
            mem_per_node_gb = 256
            walltime_min = int(45 + (forecast_hours * 2.0))
            partition = "Researches"
        else:  # WRF, ICON
            nodes = max(1, math.ceil((grid_points / 300000) * (forecast_hours / 24)))
            cpus_per_node = 32
            mem_per_node_gb = 128
            walltime_min = int(20 + (forecast_hours * 1.2))
            partition = "Researches"

        hours = walltime_min // 60
        mins = walltime_min % 60
        walltime_str = f"{hours:02d}:{mins:02d}:00"

        return {
            "model_name": model_upper,
            "nodes": nodes,
            "cpus_per_node": cpus_per_node,
            "total_cpus": nodes * cpus_per_node,
            "memory_per_node_gb": mem_per_node_gb,
            "total_memory_gb": nodes * mem_per_node_gb,
            "walltime": walltime_str,
            "partition": partition,
        }

    @staticmethod
    def generate_slurm_script(model_name: str, config: dict[str, Any]) -> str:
        """
        Generates an optimized Slurm batch script incorporating estimated resources.
        """
        res = HPCResourceOptimizer.estimate_resources(model_name, config)
        job_name = f"acf_{model_name.lower()}"
        work_dir = config.get("working_directory", f"/tmp/acf_runs/{job_name}")

        modules = config.get("modules", ["gnu9/9.4.0", "openmpi4/4.1.1"])
        module_loads = "\n".join(f"module load {m}" for m in modules)

        script = f"""#!/bin/bash
# ==============================================================================
# ACF Slurm Job Script - Auto-Generated by HPCResourceOptimizer
# Model: {res["model_name"]} | Nodes: {res["nodes"]} | Total CPUs: {res["total_cpus"]}
# ==============================================================================
#SBATCH --job-name={job_name}
#SBATCH --nodes={res["nodes"]}
#SBATCH --ntasks-per-node={res["cpus_per_node"]}
#SBATCH --mem={res["memory_per_node_gb"]}G
#SBATCH --time={res["walltime"]}
#SBATCH --partition={res["partition"]}
#SBATCH --output={work_dir}/slurm-%j.out
#SBATCH --error={work_dir}/slurm-%j.err

set -e

{module_loads}

mkdir -p {work_dir}
cd {work_dir}

echo "[ACF HPC] Starting {res["model_name"]} forecast run on $(hostname) at $(date)"
mpirun -np {res["total_cpus"]} acf_{res["model_name"].lower()}_bin --config=namelist.nml
echo "[ACF HPC] Execution completed successfully at $(date)"
"""
        return script
