"""
Real "Volcanic Ash Exercise" input dialog (Master Prompt V3 §28-29's
"ash" layer, closed 2026-09-20).

Why this dialog exists, rather than an automatic map layer
--------------------------------------------------------------
Every other AWCI map layer (Dynamic/Thermodynamic/.../Dust) is
computed automatically from ACF's own ordinary per-point
meteorological sweep - real solver state, no operator input needed.
Volcanic-ash exposure risk is fundamentally different: it depends on
whether a real eruption is actually injecting ash into the atmosphere,
which ACF has no live monitoring feed for anywhere in this codebase
(see acf.awci.volcanic_ash's own module docstring). This dialog is the
real, honest way to supply that missing real-world input - a real VAAC
bulletin's own published values, or a deliberately-entered training/
exercise scenario - never a value guessed or auto-generated by this
dialog itself (every field defaults to 0/empty, not a plausible-looking
placeholder).
"""

from __future__ import annotations

from typing import Any

from PySide6.QtWidgets import (
    QDialog,
    QDialogButtonBox,
    QDoubleSpinBox,
    QFormLayout,
    QLabel,
    QVBoxLayout,
)

from acf.gui_screen_utils import fit_dialog_to_screen


class AshExerciseDialog(QDialog):
    """Real form collecting every parameter
    `acf.awci.volcanic_ash.compute_real_ash_exposure_risk_field()`
    needs - see that function's own docstring for each field's exact
    real meaning. `get_values()` returns them as a plain dict once the
    operator accepts the dialog; the caller (ESOCWindow) is the one
    real place that dispatches the actual computation."""

    def __init__(self, parent: Any = None) -> None:
        super().__init__(parent)
        self.setWindowTitle("Volcanic Ash Exercise")
        fit_dialog_to_screen(self, 420, 420)

        outer = QVBoxLayout(self)
        intro = QLabel(
            "Enter a real VAAC bulletin's own published values, or a deliberately-entered\n"
            "training/exercise scenario - this dialog never guesses an eruption on its own."
        )
        intro.setWordWrap(True)
        outer.addWidget(intro)

        form = QFormLayout()

        self.eruption_lat_spin = _spin(-90.0, 90.0, 0.0, suffix="°")
        form.addRow("Eruption latitude", self.eruption_lat_spin)

        self.eruption_lon_spin = _spin(-180.0, 180.0, 0.0, suffix="°")
        form.addRow("Eruption longitude", self.eruption_lon_spin)

        self.eruption_rate_spin = _spin(0.0, 1_000_000.0, 0.0, suffix=" m³/s")
        self.eruption_rate_spin.setToolTip(
            "Real volumetric eruption rate (m³/s) - drives the real Mastin et al. (2009) plume height. "
            "Must be > 0 for a real eruption to be assessed."
        )
        form.addRow("Volumetric eruption rate", self.eruption_rate_spin)

        self.hours_since_spin = _spin(0.0, 240.0, 0.0, suffix=" h")
        form.addRow("Hours since eruption onset", self.hours_since_spin)

        self.wind_speed_spin = _spin(0.0, 150.0, 0.0, suffix=" m/s")
        self.wind_speed_spin.setToolTip(
            "Real wind speed at the transport-relevant level (e.g. plume height) - one real "
            "representative value for the whole plume, not per-point-varying."
        )
        form.addRow("Transport-level wind speed", self.wind_speed_spin)

        self.wind_direction_spin = _spin(0.0, 360.0, 270.0, suffix="°")
        self.wind_direction_spin.setToolTip("Meteorological convention: direction the wind is blowing FROM.")
        form.addRow("Transport-level wind direction", self.wind_direction_spin)

        self.altitude_spin = _spin(0.0, 20000.0, 8000.0, suffix=" m")
        self.altitude_spin.setToolTip("Real altitude (m) to evaluate the whole grid at, e.g. the current flight level.")
        form.addRow("Assessment altitude", self.altitude_spin)

        outer.addLayout(form)

        buttons = QDialogButtonBox(QDialogButtonBox.StandardButton.Ok | QDialogButtonBox.StandardButton.Cancel)
        buttons.accepted.connect(self.accept)
        buttons.rejected.connect(self.reject)
        outer.addWidget(buttons)

    def get_values(self) -> dict[str, float]:
        """Real, unmodified form values - see
        acf.awci.volcanic_ash.compute_real_ash_exposure_risk_field()'s
        own docstring for each key's exact real meaning."""
        return {
            "eruption_lat": self.eruption_lat_spin.value(),
            "eruption_lon": self.eruption_lon_spin.value(),
            "volumetric_eruption_rate_m3_s": self.eruption_rate_spin.value(),
            "hours_since_eruption": self.hours_since_spin.value(),
            "wind_speed_m_s": self.wind_speed_spin.value(),
            "wind_direction_deg": self.wind_direction_spin.value(),
            "point_altitude_m": self.altitude_spin.value(),
        }


def _spin(minimum: float, maximum: float, default: float, suffix: str = "") -> QDoubleSpinBox:
    spin = QDoubleSpinBox()
    spin.setRange(minimum, maximum)
    spin.setValue(default)
    spin.setDecimals(2)
    if suffix:
        spin.setSuffix(suffix)
    return spin
