"""
Golden dataset comparison - the Prompt Maître ACF v2.0's section 31-32
"Golden Datasets" gap (reports/ACF_MASTER_AUDIT_v2.md: "Aucun
tests/data/golden/ - confirmé, recherche vide").

What a "golden dataset" is here: a real, checked-in reference input/
output pair for a genuinely deterministic ACF computation (see
`tests/data/golden/`'s own README for exactly which ones and why each
is safe to snapshot). This module is the small, reusable comparison
utility every golden-dataset regression test uses instead of each
reimplementing its own JSON-loading and float-tolerance logic -
`tests/scientific/regression/test_golden_datasets.py` is the actual
test suite that uses it.

Honest scope: this is test infrastructure for *this* repository's own
suite, not a public API for downstream consumers of an installed
`acf` package - it locates `tests/data/golden/` relative to this
source file's own position in the repository tree (works for an
editable/dev install of this repo, the only way this project is
currently used - see README.md), not relative to an arbitrary
installed package location.
"""

from __future__ import annotations

import json
import math
from pathlib import Path
from typing import Any

#: This file lives at <repo_root>/src/acf/testing/golden.py.
_REPO_ROOT = Path(__file__).resolve().parents[3]
GOLDEN_DIR = _REPO_ROOT / "tests" / "data" / "golden"


class GoldenMismatchError(AssertionError):
    """Raised by assert_matches_golden() with the real path/values of the first mismatch found - not just 'not equal'."""


def golden_path(name: str) -> Path:
    """Path to `tests/data/golden/<name>` (name should end in `.json`)."""
    return GOLDEN_DIR / name


def load_golden(name: str) -> Any:
    """Load and return one golden fixture's real JSON content."""
    path = golden_path(name)
    if not path.exists():
        raise FileNotFoundError(
            f"No golden dataset at {path} - use acf.testing.golden.write_golden() to create one deliberately, "
            f"not by having a failing test silently regenerate it."
        )
    with open(path, encoding="utf-8") as f:
        return json.load(f)


def write_golden(name: str, value: Any) -> Path:
    """
    Write `value` as a new (or deliberately updated) golden fixture.

    Not called by any test in this repository - a golden file changing
    is a real decision a person (or a change under review) makes on
    purpose, never an automatic side effect of a test run. Exists so
    that decision has one real, shared, correctly-formatted way to be
    made, instead of every fixture being hand-typed or generated by a
    throwaway script.
    """
    path = golden_path(name)
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(json.dumps(value, indent=2, sort_keys=True) + "\n", encoding="utf-8")
    return path


def assert_matches_golden(
    name: str,
    actual: Any,
    rel_tol: float = 1e-9,
    abs_tol: float = 1e-9,
) -> None:
    """
    Assert `actual` matches the golden fixture `name`, recursively,
    with real floating-point tolerance (`math.isclose`) rather than
    exact equality - so a golden file survives harmless platform/
    library floating-point differences while still catching a genuine
    regression.

    Raises
    ------
    GoldenMismatchError
        Naming the exact path (e.g. "decomposition.thermodynamic") and
        both values at the first mismatch found - not just "actual !=
        expected" for the whole structure.
    """
    expected = load_golden(name)
    _compare(expected, actual, path=name, rel_tol=rel_tol, abs_tol=abs_tol)


def _compare(expected: Any, actual: Any, path: str, rel_tol: float, abs_tol: float) -> None:
    if isinstance(expected, bool) or isinstance(actual, bool):
        if expected != actual:
            raise GoldenMismatchError(f"{path}: expected {expected!r}, got {actual!r}")
        return

    if isinstance(expected, int | float) and isinstance(actual, int | float):
        if not math.isclose(float(expected), float(actual), rel_tol=rel_tol, abs_tol=abs_tol):
            raise GoldenMismatchError(f"{path}: expected {expected!r}, got {actual!r} (rel_tol={rel_tol}, abs_tol={abs_tol})")
        return

    if isinstance(expected, dict) and isinstance(actual, dict):
        missing = set(expected) - set(actual)
        extra = set(actual) - set(expected)
        if missing:
            raise GoldenMismatchError(f"{path}: actual is missing key(s) {sorted(missing)}")
        if extra:
            raise GoldenMismatchError(f"{path}: actual has unexpected extra key(s) {sorted(extra)}")
        for key in expected:
            _compare(expected[key], actual[key], f"{path}.{key}", rel_tol, abs_tol)
        return

    if isinstance(expected, list) and isinstance(actual, list):
        if len(expected) != len(actual):
            raise GoldenMismatchError(f"{path}: expected {len(expected)} item(s), got {len(actual)}")
        for i, (e, a) in enumerate(zip(expected, actual, strict=True)):
            _compare(e, a, f"{path}[{i}]", rel_tol, abs_tol)
        return

    if expected != actual:
        raise GoldenMismatchError(f"{path}: expected {expected!r}, got {actual!r}")
