"""
Atmospheric Wave Ocean Coupling Physics Module
Sprint 8.98

Coupling model between atmospheric waves and ocean dynamics.

Author: ACF Development Team
"""

from dataclasses import dataclass
from math import exp


@dataclass
class AtmosphericWaveState:
    """
    Atmospheric wave parameters.
    """

    amplitude: float
    frequency: float
    wavelength: float
    phase: float = 0.0


@dataclass
class OceanSurfaceState:
    """
    Ocean surface parameters.
    """

    sea_surface_temperature: float
    mixed_layer_depth: float
    current_velocity: float
    surface_stress: float


@dataclass
class WaveOceanCouplingResult:
    """
    Coupled system response.
    """

    momentum_exchange: float
    heat_flux_exchange: float
    energy_transfer: float
    damping_factor: float
    climate_interaction_index: float


class AtmosphericWaveOceanCoupling:
    """
    Physics engine describing atmosphere-ocean wave coupling.
    """

    def __init__(self):
        self.name = "Atmospheric Wave Ocean Coupling"

    def calculate_momentum_exchange(self, wave: AtmosphericWaveState, ocean: OceanSurfaceState) -> float:
        """
        Momentum transfer between atmosphere and ocean.
        """

        return wave.amplitude * wave.frequency * ocean.surface_stress

    def calculate_heat_flux_exchange(self, wave: AtmosphericWaveState, ocean: OceanSurfaceState) -> float:
        """
        Heat exchange generated by coupling.
        """

        temperature_effect = abs(ocean.sea_surface_temperature - 273.15)

        return wave.amplitude * temperature_effect * 0.01

    def calculate_energy_transfer(self, wave: AtmosphericWaveState, ocean: OceanSurfaceState) -> float:
        """
        Atmospheric wave energy transfer to ocean.
        """

        return 0.5 * wave.amplitude**2 * wave.frequency * ocean.mixed_layer_depth

    def calculate_wave_damping(self, ocean: OceanSurfaceState) -> float:
        """
        Ocean damping effect on atmospheric waves.
        """

        return exp(-abs(ocean.current_velocity) * 0.01)

    def simulate(self, wave: AtmosphericWaveState, ocean: OceanSurfaceState) -> WaveOceanCouplingResult:
        """
        Full atmosphere-ocean coupling simulation.
        """

        momentum = self.calculate_momentum_exchange(wave, ocean)

        heat = self.calculate_heat_flux_exchange(wave, ocean)

        energy = self.calculate_energy_transfer(wave, ocean)

        damping = self.calculate_wave_damping(ocean)

        climate_index = (momentum + heat + energy) * damping

        return WaveOceanCouplingResult(
            momentum_exchange=momentum,
            heat_flux_exchange=heat,
            energy_transfer=energy,
            damping_factor=damping,
            climate_interaction_index=climate_index,
        )
