"""Neural Operator AI Simulation Accelerator."""

from enum import Enum
from typing import TYPE_CHECKING, Any

import numpy as np

if TYPE_CHECKING:
    from acf.ai.simulation.fno_model import FourierNeuralOperator2D


class AIFrameworkType(Enum):
    """Supported Neural Operator architectures."""

    FOURIER_NEURAL_OPERATOR = "FNO"
    GRAPH_NEURAL_NETWORK = "GNN"
    TRANSFORMER_WEATHER_MODEL = "Transformer"
    PHYSICS_AI_SURROGATE = "Physics-AI-Surrogate"


class NeuralOperatorEngine:
    """AI Simulation Accelerator evaluating:

    AI_surrogate(X(t)) ~ Numerical_Solver(X(t))

    NOTE (correction — mislabeled, not fabricated): "acceleration_factor
    = 1000.0" and predict_next_state()'s FOURIER_NEURAL_OPERATOR branch
    used to claim to BE a Fourier Neural Operator while having zero
    learnable parameters - it was (and predict_next_state() below still
    is, for the general multi-field case) a fixed, untrained, per-call
    exponential decay of every Fourier mode (`field_fft *= exp(-1e-4*dt)`),
    identical on every call regardless of any training - not the actual
    defining characteristic of an FNO (a learned linear operator on the
    Fourier modes, fit by backpropagation to real target data - see Li et
    al. 2020). "1000x speedup" was never benchmarked against anything.

    A REAL, trained FNO now exists (acf.ai.simulation.fno_model.
    FourierNeuralOperator2D, acf.ai.simulation.fno_training) but is
    correctly scoped to what it was actually trained on - near-surface
    temperature only, trained on trajectories generated by ACF's own
    CoupledEarthSolver (this session has no access to real ARPEGE/ERA5
    archives - see fno_model.py's own docstring). predict_surface_
    temperature() below uses it genuinely, with an honest "untrained"
    status when no checkpoint is loaded. predict_next_state() keeps its
    old behaviour for the general heterogeneous multi-field case (still
    not a trained model for any of those fields) - not deleted, per
    project convention, but no longer presented as unrelated to this note.
    """

    def __init__(
        self,
        architecture: AIFrameworkType = AIFrameworkType.FOURIER_NEURAL_OPERATOR,
        fno_checkpoint_path: str | None = None,
    ) -> None:
        self.architecture = architecture
        self.acceleration_factor = None  # NOTE (correction): never benchmarked - was a fabricated "1000.0" constant.

        self._fno_model: FourierNeuralOperator2D | None = None
        self._fno_checkpoint: dict[str, Any] | None = None
        if fno_checkpoint_path is not None:
            self.load_trained_surrogate(fno_checkpoint_path)

    def load_trained_surrogate(self, checkpoint_path: str, modes1: int | None = None, modes2: int | None = None) -> None:
        """Load a real trained FourierNeuralOperator2D checkpoint (see
        acf.ai.simulation.fno_training.save_checkpoint/train_fno).
        modes1/modes2 are read from the checkpoint itself unless
        explicitly overridden."""
        from acf.ai.simulation.fno_training import load_checkpoint

        self._fno_model, self._fno_checkpoint = load_checkpoint(checkpoint_path, modes1=modes1, modes2=modes2)

    def predict_surface_temperature(self, temperature_field: np.ndarray, dt: float = 3600.0) -> dict[str, Any]:
        """Predict T(t + dt) for a single near-surface temperature field
        using the real trained FNO surrogate, if one is loaded.

        Parameters
        ----------
        temperature_field : np.ndarray, shape (n_lat, n_lon).
        dt : float
            Informational only - the loaded model was trained for a
            fixed dt (see its checkpoint); it does not condition on dt.

        Returns
        -------
        dict with "predicted_field" (np.ndarray or None) and "status".
        """
        model = self._fno_model
        checkpoint = self._fno_checkpoint
        if model is None or checkpoint is None:
            return {
                "predicted_field": None,
                "status": "NOT_PREDICTED_NO_TRAINED_SURROGATE_LOADED",
                "requested_dt": dt,
            }

        import torch

        mean = checkpoint["normalization_mean"]
        std = checkpoint["normalization_std"]

        x = torch.from_numpy(temperature_field.astype(np.float32))[None, None, :, :]
        x_norm = (x - mean) / std

        model.eval()
        with torch.no_grad():
            y_norm = model(x_norm)

        predicted = (y_norm * std + mean).squeeze(0).squeeze(0).numpy()

        return {
            "predicted_field": predicted,
            "status": "PREDICTED_BY_TRAINED_SURROGATE",
            "surrogate_final_train_loss": checkpoint.get("final_train_loss"),
            "surrogate_final_val_loss": checkpoint.get("final_val_loss"),
        }

    def predict_next_state(self, state: dict[str, np.ndarray], dt: float = 3600.0) -> dict[str, np.ndarray]:
        """Predict state evolution X(t + dt) for the general, heterogeneous
        multi-field state dict.

        NOTE: unlike predict_surface_temperature() above, no trained
        surrogate exists for this general multi-field case - see this
        class's own NOTE (correction) docstring. Kept as-is (not deleted),
        but this is a fixed spectral-decay proxy, not a learned prediction.

        Args:
            state (Dict[str, np.ndarray]): Current state dictionary.
            dt (float): Timestep in seconds.

        Returns:
            Dict[str, np.ndarray]: Proxy state prediction (not from a
            trained model - see this method's own NOTE above).
        """
        predicted_state = {}

        for key, field in state.items():
            if not isinstance(field, np.ndarray):
                predicted_state[key] = field
                continue

            if self.architecture == AIFrameworkType.FOURIER_NEURAL_OPERATOR:
                # 2D/3D Spectral Fourier truncation & linear operator approximation
                field_fft = np.fft.rfftn(field)
                # Keep low frequency modes
                field_fft *= np.exp(-1e-4 * dt)
                field_next = np.fft.irfftn(field_fft, s=field.shape, axes=list(range(field.ndim)))
            else:
                # GNN/Transformer spatial smoothing proxy
                field_next = field + 0.001 * np.random.normal(size=field.shape)

            predicted_state[key] = field_next

        return predicted_state
