"""
Atmospheric Complexity Framework (ACF)

Physical Parameters Canonical Definitions Database
"""

from acf.science.parameters.physical_parameter import PhysicalParameter

PHYSICAL_PARAMETERS = [
    # ----------------------------------------------------
    # ATMOSPHERE
    # ----------------------------------------------------
    PhysicalParameter(
        key="temperature",
        name="Température de l'Air",
        symbol="T",
        domain="Atmosphère",
        unit="K",
        description="Mesure de l'énergie cinétique moyenne des molécules d'air.",
        physical_meaning="Variable d'état thermodynamique fondamentale régissant la pression de vapeur et la stabilité.",
        dependencies=[],
        related_laws=["ideal_gas_law", "stefan_boltzmann", "isa_temperature_profile"],
        calculation_methods=["acf.science.temperature"],
    ),
    PhysicalParameter(
        key="pressure",
        name="Pression Atmosphérique",
        symbol="p",
        domain="Atmosphère",
        unit="Pa",
        description="Poids de la colonne d'air par unité de surface.",
        physical_meaning="Force mécanique de compression exercée par l'atmosphère sur les surfaces et les parcelles d'air.",
        dependencies=[],
        related_laws=["hydrostatic_equilibrium", "ideal_gas_law", "isa_pressure_profile"],
        calculation_methods=["acf.science.pressure"],
    ),
    PhysicalParameter(
        key="density",
        name="Masse Volumique de l'Air",
        symbol="rho",
        domain="Atmosphère",
        unit="kg/m³",
        description="Masse d'air contenue dans un volume unitaire.",
        physical_meaning="Facteur déterminant pour la portance aérodynamique et les forces de flottabilité convective.",
        dependencies=["temperature", "pressure"],
        related_laws=["ideal_gas_law", "hydrostatic_equilibrium"],
        calculation_methods=["acf.science.air_density.AirDensity.calculate"],
    ),
    PhysicalParameter(
        key="geopotential_height",
        name="Altitude Géopotentielle",
        symbol="zg",
        domain="Atmosphère",
        unit="m",
        description="Altitude ajustée selon les variations spatiales de la pesanteur terrestre.",
        physical_meaning="Hauteur physique équivalente au travail nécessaire pour élever une masse unitaire du niveau de la mer.",
        dependencies=["pressure", "temperature"],
        related_laws=["hydrostatic_equilibrium"],
        calculation_methods=["acf.science.geopotential_height"],
    ),
    PhysicalParameter(
        key="humidity",
        name="Humidité Relative",
        symbol="RH",
        domain="Atmosphère",
        unit="%",
        description="Rapport entre la pression partielle de vapeur d'eau et la pression de vapeur saturante.",
        physical_meaning="Indicateur de la saturation de l'air en vapeur d'eau et de la probabilité de condensation/nuages.",
        dependencies=["temperature", "pressure"],
        related_laws=["clausius_clapeyron"],
        calculation_methods=["acf.science.relative_humidity"],
    ),
    PhysicalParameter(
        key="mixing_ratio",
        name="Rapport de Mélange de Vapeur d'Eau",
        symbol="w",
        domain="Atmosphère",
        unit="kg/kg",
        description="Masse de vapeur d'eau par unité de masse d'air sec.",
        physical_meaning="Quantité conservée lors des déplacements verticaux adiabatiques secs.",
        dependencies=["humidity", "pressure"],
        related_laws=["ideal_gas_law"],
        calculation_methods=["acf.science.mixing_ratio"],
    ),
    PhysicalParameter(
        key="virtual_temperature",
        name="Température Virtuelle",
        symbol="Tv",
        domain="Atmosphère",
        unit="K",
        description="Température théorique de l'air sec ayant la même masse volumique que l'air humide.",
        physical_meaning="Prend en compte la plus faible densité de la vapeur d'eau par rapport à l'air sec dans les calculs de flottabilité.",
        dependencies=["temperature", "humidity"],
        related_laws=["virtual_temperature", "ideal_gas_law"],
        calculation_methods=["acf.science.virtual_potential_temperature"],
    ),

    # ----------------------------------------------------
    # DYNAMICS
    # ----------------------------------------------------
    PhysicalParameter(
        key="wind_u",
        name="Composante Zonal du Vent (Est-Ouest)",
        symbol="u",
        domain="Dynamique Atmosphérique",
        unit="m/s",
        description="Vitesse du vent le long du parallèle terrestre (positif vers l'Est).",
        physical_meaning="Transport advectif zonal de chaleur, d'humidité et d'impulsion.",
        dependencies=[],
        related_laws=["geostrophic_balance", "vector_divergence"],
        calculation_methods=["acf.science.dynamics"],
    ),
    PhysicalParameter(
        key="wind_v",
        name="Composante Méridienne du Vent (Nord-Sud)",
        symbol="v",
        domain="Dynamique Atmosphérique",
        unit="m/s",
        description="Vitesse du vent le long du méridien terrestre (positif vers le Nord).",
        physical_meaning="Transport advectif méridien régissant les échanges thermiques équateur-pôle.",
        dependencies=[],
        related_laws=["geostrophic_balance", "vector_divergence"],
        calculation_methods=["acf.science.dynamics"],
    ),
    PhysicalParameter(
        key="vorticity",
        name="Vorticité Relative",
        symbol="zeta",
        domain="Dynamique Atmosphérique",
        unit="s⁻¹",
        description="Composante verticale du rotationnel du champ de vent horizontal.",
        physical_meaning="Mesure la rotation locale de la masse d'air (cyclonique > 0 dans l'hémisphère Nord).",
        dependencies=["wind_u", "wind_v"],
        related_laws=["absolute_vorticity", "vector_curl"],
        calculation_methods=["acf.science.dynamics"],
    ),
    PhysicalParameter(
        key="divergence",
        name="Divergence Horizontale du Vent",
        symbol="delta",
        domain="Dynamique Atmosphérique",
        unit="s⁻¹",
        description="Taux d'étalement horizontal du champ de vitesse du fluide.",
        physical_meaning="La divergence en altitude provoque des mouvements verticaux ascendants (convection) par continuité.",
        dependencies=["wind_u", "wind_v"],
        related_laws=["vector_divergence", "mass_conservation"],
        calculation_methods=["acf.science.divergence.Divergence.calculate"],
    ),
    PhysicalParameter(
        key="potential_vorticity",
        name="Vorticité Potentielle d'Ertel",
        symbol="PV",
        domain="Dynamique Atmosphérique",
        unit="PVU",
        description="Produit scalaire du vecteur vorticité absolue et du gradient de température potentielle.",
        physical_meaning="Grandeur dynamique conservée sous processus adiabatiques, traceur des anomalies de la tropopause.",
        dependencies=["vorticity", "potential_temperature", "density"],
        related_laws=["ertel_potential_vorticity"],
        calculation_methods=["acf.science.potential_vorticity"],
    ),
    PhysicalParameter(
        key="deformation",
        name="Déformation du Champ de Vent",
        symbol="D_def",
        domain="Dynamique Atmosphérique",
        unit="s⁻¹",
        description="Taux d'étirement et de cisaillement du champ de vent sans changement de surface.",
        physical_meaning="Moteur principal de la frontogenèse atmosphérique et du resserrement des gradients thermiques.",
        dependencies=["wind_u", "wind_v"],
        related_laws=["vector_gradient"],
        calculation_methods=["acf.science.frontogenesis"],
    ),

    # ----------------------------------------------------
    # THERMODYNAMICS
    # ----------------------------------------------------
    PhysicalParameter(
        key="potential_temperature",
        name="Température Potentielle",
        symbol="theta",
        domain="Thermodynamique",
        unit="K",
        description="Température qu'aurait une parcelle amenée adiabatiquement à 1000 hPa.",
        physical_meaning="Indicateur de la stabilité statique dry-adiabatic de l'atmosphère (dtheta/dz > 0 est stable).",
        dependencies=["temperature", "pressure"],
        related_laws=["potential_temperature", "adiabatic_transformation"],
        calculation_methods=["acf.science.potential_temperature.PotentialTemperature.calculate"],
    ),
    PhysicalParameter(
        key="equivalent_potential_temperature",
        name="Température Potentielle Équivalente",
        symbol="theta_e",
        domain="Thermodynamique",
        unit="K",
        description="Température potentielle après condensation totale et libération de toute la chaleur latente.",
        physical_meaning="Mesure l'énergie enthalpique totale (chaleur sensible + vapeur d'eau) contenue dans la masse d'air.",
        dependencies=["potential_temperature", "humidity"],
        related_laws=["first_law_thermodynamics", "clausius_clapeyron"],
        calculation_methods=["acf.science.equivalent_potential_temperature"],
    ),
    PhysicalParameter(
        key="CAPE",
        name="Énergie Potentielle Convective Disponible (CAPE)",
        symbol="CAPE",
        domain="Thermodynamique",
        unit="J/kg",
        description="Intégrale de la force de flottabilité positive exercée sur une parcelle d'air ascendante.",
        physical_meaning="Potentiel d'accélération verticale des courants ascendants lors d'orages violents.",
        dependencies=["temperature", "humidity", "pressure"],
        related_laws=["first_law_thermodynamics", "hydrostatic_equilibrium"],
        calculation_methods=["acf.science.cape.CAPE.calculate"],
    ),
    PhysicalParameter(
        key="CIN",
        name="Inhibition Convective (CIN)",
        symbol="CIN",
        domain="Thermodynamique",
        unit="J/kg",
        description="Énergie négative nécessaire pour élever une parcelle du sol jusqu'au niveau de libre convection (LFC).",
        physical_meaning="Barrière d'inversion thermique bloquant le déclenchement prématuré de la convection.",
        dependencies=["temperature", "humidity", "pressure"],
        related_laws=["first_law_thermodynamics"],
        calculation_methods=["acf.science.cin.CIN.calculate"],
    ),

    # ----------------------------------------------------
    # MICROPHYSICS
    # ----------------------------------------------------
    PhysicalParameter(
        key="cloud_water",
        name="Eau Liquide Nuageuse",
        symbol="qc",
        domain="Microphysique",
        unit="kg/kg",
        description="Rapport de mélange des gouttelettes d'eau condensées en suspension.",
        physical_meaning="Masse d'eau liquide maintenue en suspension par la traînée de l'air avant précipitation.",
        dependencies=["humidity", "temperature"],
        related_laws=["kessler_autoconversion"],
        calculation_methods=["acf.model4d.physics.atmospheric_cloud_microphysics"],
    ),
    PhysicalParameter(
        key="rain_water",
        name="Eau de Pluie",
        symbol="qr",
        domain="Microphysique",
        unit="kg/kg",
        description="Rapport de mélange des gouttes de pluie précipitantes.",
        physical_meaning="Masse d'eau liquide tombant sous l'effet de la gravité.",
        dependencies=["cloud_water"],
        related_laws=["collection_coalescence"],
        calculation_methods=["acf.model4d.physics.atmospheric_cloud_microphysics"],
    ),
    PhysicalParameter(
        key="ice",
        name="Glace Nuageuse",
        symbol="qi",
        domain="Microphysique",
        unit="kg/kg",
        description="Rapport de mélange des cristaux de glace primaires.",
        physical_meaning="Phase solide des nuages hauts (cirrus) et des sommets d'orages.",
        dependencies=["temperature", "cloud_water"],
        related_laws=["ice_crystal_nucleation"],
        calculation_methods=["acf.model4d.physics.atmospheric_cloud_microphysics"],
    ),
    PhysicalParameter(
        key="snow",
        name="Neige",
        symbol="qs",
        domain="Microphysique",
        unit="kg/kg",
        description="Rapport de mélange des agrégats de cristaux de neige précipitant.",
        physical_meaning="Hydrométéore solide tombant à faible vitesse limite de chute.",
        dependencies=["ice", "temperature"],
        related_laws=["ice_crystal_nucleation"],
        calculation_methods=["acf.model4d.physics.atmospheric_cloud_microphysics"],
    ),
    PhysicalParameter(
        key="graupel",
        name="Grésil / Grêle",
        symbol="qg",
        domain="Microphysique",
        unit="kg/kg",
        description="Rapport de mélange des billes de glace dense formées par givrage.",
        physical_meaning="Précipitation solide dense associée à des courants ascendants très intenses.",
        dependencies=["rain_water", "ice"],
        related_laws=["collection_coalescence"],
        calculation_methods=["acf.model4d.physics.atmospheric_cloud_microphysics"],
    ),

    # ----------------------------------------------------
    # RADIATION
    # ----------------------------------------------------
    PhysicalParameter(
        key="solar_flux",
        name="Flux Solaire Incidents (Ondes Courtes)",
        symbol="F_sol",
        domain="Rayonnement",
        unit="W/m²",
        description="Énergie électromagnétique d'origine solaire reçue par unité de surface.",
        physical_meaning="Source primaire d'énergie réchauffant la surface terrestre et l'atmosphère.",
        dependencies=["temperature"],
        related_laws=["planck_law", "beer_lambert"],
        calculation_methods=["acf.model4d.physics.atmospheric_radiation_dynamics"],
    ),
    PhysicalParameter(
        key="infrared_flux",
        name="Flux Infrarouge Terrestre (Ondes Longues)",
        symbol="F_IR",
        domain="Rayonnement",
        unit="W/m²",
        description="Énergie électromagnétique Infrarouge émise par la Terre et l'atmosphère.",
        physical_meaning="Refroidissement radiatif de la planète compensé par l'effet de serre.",
        dependencies=["temperature"],
        related_laws=["stefan_boltzmann"],
        calculation_methods=["acf.model4d.physics.atmospheric_radiation_dynamics"],
    ),
    PhysicalParameter(
        key="albedo",
        name="Albédo de Surface",
        symbol="alpha",
        domain="Rayonnement",
        unit="dimensionless",
        description="Fraction du rayonnement solaire incident réfléchie par la surface.",
        physical_meaning="Détermine la quantité d'énergie solaire absorbée par le sol (neige ~ 0.8, océan ~ 0.06).",
        dependencies=["solar_flux"],
        related_laws=["beer_lambert"],
        calculation_methods=["acf.model4d.physics.atmospheric_radiation_dynamics"],
    ),

    # ----------------------------------------------------
    # AERONAUTICS
    # ----------------------------------------------------
    PhysicalParameter(
        key="speed_of_sound",
        name="Vitesse du Son dans l'Air",
        symbol="a",
        domain="Aéronautique",
        unit="m/s",
        description="Vitesse de propagation des ondes de compression acoustique.",
        physical_meaning="Référence pour l'écoulement compressible autour des aéronefs.",
        dependencies=["temperature"],
        related_laws=["speed_of_sound"],
        calculation_methods=["acf.science.laws.aeronautics"],
    ),
    PhysicalParameter(
        key="mach",
        name="Nombre de Mach",
        symbol="M",
        domain="Aéronautique",
        unit="dimensionless",
        description="Rapport entre la vitesse vraie de l'aéronef et la vitesse locale du son.",
        physical_meaning="Régime de vol (subsonique, transsonique, supersonique).",
        dependencies=["wind_u", "speed_of_sound"],
        related_laws=["mach_number"],
        calculation_methods=["acf.science.laws.aeronautics"],
    ),
    PhysicalParameter(
        key="reynolds",
        name="Nombre de Reynolds",
        symbol="Re",
        domain="Aéronautique",
        unit="dimensionless",
        description="Rapport des forces d'inertie aux forces de viscosité.",
        physical_meaning="Détermine le régime de la couche limite aérodynamique (laminaire ou turbulent).",
        dependencies=["density", "wind_u"],
        related_laws=["reynolds_number"],
        calculation_methods=["acf.science.laws.aeronautics"],
    ),
    PhysicalParameter(
        key="lift_coefficient",
        name="Coefficient de Portance",
        symbol="CL",
        domain="Aéronautique",
        unit="dimensionless",
        description="Coefficient adimensionnel de la force de portance générée par la voilure.",
        physical_meaning="Dépend de l'angle d'attaque de l'aile et du profil aérodynamique.",
        dependencies=["density", "wind_u"],
        related_laws=["aerodynamic_lift"],
        calculation_methods=["acf.science.laws.aeronautics"],
    ),
    PhysicalParameter(
        key="drag_coefficient",
        name="Coefficient de Traînée",
        symbol="CD",
        domain="Aéronautique",
        unit="dimensionless",
        description="Coefficient adimensionnel de la force de résistance à l'avancement.",
        physical_meaning="Somme de la traînée de forme, de frottement et induite.",
        dependencies=["density", "wind_u"],
        related_laws=["aerodynamic_drag"],
        calculation_methods=["acf.science.laws.aeronautics"],
    ),
]
