"""
Atmospheric Complexity Framework (ACF)

Physical Parameters Canonical Definitions Database
"""

from acf.science.parameters.physical_parameter import PhysicalParameter

PHYSICAL_PARAMETERS = [
    # ----------------------------------------------------
    # ATMOSPHERE
    # ----------------------------------------------------
    PhysicalParameter(
        key="temperature",
        name="Température de l'Air",
        symbol="T",
        domain="Atmosphère",
        unit="K",
        description="Mesure de l'énergie cinétique moyenne des molécules d'air.",
        physical_meaning="Variable d'état thermodynamique fondamentale régissant la pression de vapeur et la stabilité.",
        abbreviation="T",
        category="Thermodynamique",
        alternative_units=["°C", "°F"],
        dimensions="[K]",
        governing_equation="p = rho * R_d * T",
        latex_equation=r"p = \rho R_d T",
        variables={"p": "Pression (Pa)", "rho": "Densité (kg/m³)", "Rd": "Constante de l'air sec"},
        valid_range="180 K to 330 K",
        cf_standard_name="air_temperature",
        grib2_code="0,0,0",
        bufr_code="0 12 001",
        netcdf_name="ta",
        observation_systems=["Station météo", "Radiosondage", "Satellite IR", "AMDAR"],
        numerical_models=["IFS", "AROME", "ARPEGE", "ICON", "GFS", "WRF"],
        satellite_products=["IASI", "CrIS", "SEVIRI", "MODIS"],
        aviation_applications=["OAT", "ISA Deviation", "Performance décollage"],
        climatology_applications=["Anomalie thermique mondiale", "GISS", "ERA5"],
        references=["WMO-No. 8 Guide to Meteorological Instruments", "Bohren & Albrecht (1998)"],
        dependencies=[],
        related_laws=["ideal_gas_law", "stefan_boltzmann", "isa_temperature_profile"],
        calculation_methods=["acf.science.temperature"],
    ),
    PhysicalParameter(
        key="pressure",
        name="Pression Atmosphérique",
        symbol="p",
        domain="Atmosphère",
        unit="Pa",
        description="Poids de la colonne d'air par unité de surface.",
        physical_meaning="Force mécanique de compression exercée par l'atmosphère sur les surfaces et les parcelles d'air.",
        abbreviation="PRES",
        category="Thermodynamique",
        alternative_units=["hPa", "bar", "mmHg", "inHg"],
        dimensions="[M L⁻¹ T⁻²]",
        governing_equation="dp/dz = - rho * g",
        latex_equation=r"\frac{\partial p}{\partial z} = -\rho g",
        variables={"rho": "Densité (kg/m³)", "g": "Gravité (9.81 m/s²)"},
        valid_range="10000 Pa to 108000 Pa",
        cf_standard_name="air_pressure",
        grib2_code="0,3,0",
        bufr_code="0 10 004",
        netcdf_name="ps",
        observation_systems=["Baromètre", "Radiosondage", "GPS-RO"],
        numerical_models=["IFS", "AROME", "ARPEGE", "ICON", "GFS", "WRF"],
        satellite_products=["GNSS-RO", "ASCAT Surface Pressure"],
        aviation_applications=["QNH", "QFE", "QFF", "Altimétrie"],
        climatology_applications=["Centres d'action synoptiques", "Oscillations NAO/AO"],
        references=["WMO-No. 8", "Holton & Hakim (2012)"],
        dependencies=[],
        related_laws=["hydrostatic_equilibrium", "ideal_gas_law", "isa_pressure_profile"],
        calculation_methods=["acf.science.pressure"],
    ),
    PhysicalParameter(
        key="density",
        name="Masse Volumique de l'Air",
        symbol="rho",
        domain="Atmosphère",
        unit="kg/m³",
        description="Masse d'air contenue dans un volume unitaire.",
        physical_meaning="Facteur déterminant pour la portance aérodynamique et les forces de flottabilité convective.",
        abbreviation="RHO",
        category="Thermodynamique",
        alternative_units=["g/cm³"],
        dimensions="[M L⁻³]",
        governing_equation="rho = p / (R_d * T_v)",
        latex_equation=r"\rho = \frac{p}{R_d T_v}",
        variables={"p": "Pression (Pa)", "Tv": "Température virtuelle (K)"},
        valid_range="0.1 kg/m³ to 1.4 kg/m³",
        cf_standard_name="air_density",
        grib2_code="0,3,10",
        bufr_code="0 10 010",
        netcdf_name="rho",
        observation_systems=["Calculé via P et T"],
        numerical_models=["IFS", "AROME", "ICON", "WRF"],
        aviation_applications=["Density Altitude", "Portance des ailes"],
        references=["WMO Atmospheric Physics", "ICAO Standard Atmosphere Doc 7488"],
        dependencies=["temperature", "pressure"],
        related_laws=["ideal_gas_law", "hydrostatic_equilibrium"],
        calculation_methods=["acf.science.air_density.AirDensity.calculate"],
    ),
    PhysicalParameter(
        key="geopotential_height",
        name="Altitude Géopotentielle",
        symbol="zg",
        domain="Atmosphère",
        unit="m",
        description="Altitude ajustée selon les variations spatiales de la pesanteur terrestre.",
        physical_meaning="Hauteur physique équivalente au travail nécessaire pour élever une masse unitaire du niveau de la mer.",
        abbreviation="GPH",
        category="Dynamique",
        alternative_units=["gpm"],
        dimensions="[L]",
        governing_equation="Z = (1 / g0) * int_0^z g(phi, z') dz'",
        latex_equation=r"Z = \frac{1}{g_0} \int_0^z g(\phi, z^\prime) dz^\prime",
        variables={"g0": "9.80665 m/s²", "z": "Altitude géométrique"},
        valid_range="-100 m to 80000 m",
        cf_standard_name="geopotential_height",
        grib2_code="0,3,5",
        bufr_code="0 10 009",
        netcdf_name="gh",
        observation_systems=["Radiosondage", "Satellite Sounder"],
        numerical_models=["IFS", "ARPEGE", "GFS", "ICON"],
        aviation_applications=["Niveaux de vol FL (Flight Levels)"],
        references=["WMO No. 8", "AMS Glossary"],
        dependencies=["pressure", "temperature"],
        related_laws=["hydrostatic_equilibrium"],
        calculation_methods=["acf.science.geopotential_height"],
    ),
    PhysicalParameter(
        key="humidity",
        name="Humidité Relative",
        symbol="RH",
        domain="Atmosphère",
        unit="%",
        description="Rapport entre la pression partielle de vapeur d'eau et la pression de vapeur saturante.",
        physical_meaning="Indicateur de la saturation de l'air en vapeur d'eau et de la probabilité de condensation/nuages.",
        abbreviation="RH",
        category="Thermodynamique",
        alternative_units=["fraction (0 to 1)"],
        dimensions="[1]",
        governing_equation="RH = (e / e_s(T)) * 100",
        latex_equation=r"\text{RH} = \frac{e}{e_s(T)} \times 100\%",
        variables={"e": "Pression de vapeur d'eau", "es": "Pression de vapeur saturante"},
        valid_range="0% to 100%",
        cf_standard_name="relative_humidity",
        grib2_code="0,1,1",
        bufr_code="0 13 003",
        netcdf_name="hur",
        observation_systems=["Hygromètre", "Station météo", "Radiosondage"],
        numerical_models=["IFS", "AROME", "ICON", "GFS"],
        satellite_products=["SEVIRI WV Channel", "IASI Humidity Profile"],
        aviation_applications=["Givrage carburateur", "Brouillard de piste"],
        references=["WMO Guide to Instruments", "Bolton (1980)"],
        dependencies=["temperature", "pressure"],
        related_laws=["clausius_clapeyron"],
        calculation_methods=["acf.science.relative_humidity"],
    ),
    PhysicalParameter(
        key="mixing_ratio",
        name="Rapport de Mélange de Vapeur d'Eau",
        symbol="w",
        domain="Atmosphère",
        unit="kg/kg",
        description="Masse de vapeur d'eau par unité de masse d'air sec.",
        physical_meaning="Quantité conservée lors des déplacements verticaux adiabatiques secs.",
        abbreviation="MIXR",
        category="Thermodynamique",
        alternative_units=["g/kg"],
        dimensions="[M M⁻¹]",
        governing_equation="w = 0.622 * e / (p - e)",
        latex_equation=r"w = \epsilon \frac{e}{p - e}",
        variables={"e": "Pression de vapeur Pa", "p": "Pression totale Pa"},
        valid_range="0 kg/kg to 0.04 kg/kg",
        cf_standard_name="humidity_mixing_ratio",
        grib2_code="0,1,2",
        bufr_code="0 13 002",
        netcdf_name="wmx",
        observation_systems=["Radiosondage", "Sondes d'humidité"],
        numerical_models=["AROME", "WRF", "Meso-NH"],
        references=["WMO Atmospheric Thermodynamics"],
        dependencies=["humidity", "pressure"],
        related_laws=["ideal_gas_law"],
        calculation_methods=["acf.science.mixing_ratio"],
    ),
    PhysicalParameter(
        key="virtual_temperature",
        name="Température Virtuelle",
        symbol="Tv",
        domain="Atmosphère",
        unit="K",
        description="Température théorique de l'air sec ayant la même masse volumique que l'air humide.",
        physical_meaning="Prend en compte la plus faible densité de la vapeur d'eau par rapport à l'air sec dans les calculs de flottabilité.",
        abbreviation="Tv",
        category="Thermodynamique",
        alternative_units=["°C"],
        dimensions="[K]",
        governing_equation="Tv = T * (1 + 0.608 * q)",
        latex_equation=r"T_v = T(1 + 0.608 q)",
        variables={"T": "Température (K)", "q": "Humidité spécifique (kg/kg)"},
        valid_range="180 K to 340 K",
        cf_standard_name="virtual_temperature",
        grib2_code="0,0,1",
        bufr_code="0 12 002",
        netcdf_name="tv",
        observation_systems=["Calculé via T et q"],
        numerical_models=["IFS", "AROME", "WRF", "ICON"],
        references=["Emanuel (1994)", "WMO"],
        dependencies=["temperature", "humidity"],
        related_laws=["virtual_temperature", "ideal_gas_law"],
        calculation_methods=["acf.science.virtual_potential_temperature"],
    ),
    # ----------------------------------------------------
    # DYNAMICS
    # ----------------------------------------------------
    PhysicalParameter(
        key="wind_u",
        name="Composante Zonale du Vent (Est-Ouest)",
        symbol="u",
        domain="Dynamique",
        unit="m/s",
        description="Vitesse du vent le long du parallèle terrestre (positif vers l'Est).",
        physical_meaning="Transport advectif zonal de chaleur, d'humidité et d'impulsion.",
        abbreviation="UGRD",
        category="Dynamique",
        alternative_units=["km/h", "knots"],
        dimensions="[L T⁻¹]",
        valid_range="-150 m/s to 150 m/s",
        cf_standard_name="eastward_wind",
        grib2_code="0,2,2",
        bufr_code="0 11 003",
        netcdf_name="ua",
        observation_systems=["Anémomètre", "Radar Doppler", "ASCAT"],
        numerical_models=["IFS", "AROME", "ARPEGE", "GFS", "ICON"],
        satellite_products=["ASCAT", "AMV"],
        radar_products=["Doppler VAD"],
        aviation_applications=["Vent arrière/bout"],
        references=["WMO-No. 8", "Holton & Hakim (2012)"],
        dependencies=[],
        related_laws=["geostrophic_balance", "vector_divergence"],
        calculation_methods=["acf.science.dynamics"],
    ),
    PhysicalParameter(
        key="wind_v",
        name="Composante Méridienne du Vent (Nord-Sud)",
        symbol="v",
        domain="Dynamique",
        unit="m/s",
        description="Vitesse du vent le long du méridien terrestre (positif vers le Nord).",
        physical_meaning="Transport advectif méridien régissant les échanges thermiques équateur-pôle.",
        abbreviation="VGRD",
        category="Dynamique",
        alternative_units=["km/h", "knots"],
        dimensions="[L T⁻¹]",
        valid_range="-150 m/s to 150 m/s",
        cf_standard_name="northward_wind",
        grib2_code="0,2,3",
        bufr_code="0 11 004",
        netcdf_name="va",
        observation_systems=["Anémomètre", "Radar Doppler", "ASCAT"],
        numerical_models=["IFS", "AROME", "ARPEGE", "GFS", "ICON"],
        satellite_products=["ASCAT", "AMV"],
        radar_products=["Doppler VAD"],
        aviation_applications=["Vent traversier"],
        references=["WMO-No. 8"],
        dependencies=[],
        related_laws=["geostrophic_balance", "vector_divergence"],
        calculation_methods=["acf.science.dynamics"],
    ),
    PhysicalParameter(
        key="vorticity",
        name="Vorticité Relative",
        symbol="zeta",
        domain="Dynamique",
        unit="s⁻¹",
        description="Composante verticale du rotationnel du champ de vent horizontal.",
        physical_meaning="Mesure la rotation locale de la masse d'air (cyclonique > 0 dans l'hémisphère Nord).",
        abbreviation="VORT",
        category="Dynamique",
        dimensions="[T⁻¹]",
        governing_equation="zeta = dv/dx - du/dy",
        latex_equation=r"\zeta = \frac{\partial v}{\partial x} - \frac{\partial u}{\partial y}",
        valid_range="-1e-2 s⁻¹ to 1e-2 s⁻¹",
        cf_standard_name="atmosphere_relative_vorticity",
        grib2_code="0,2,12",
        bufr_code="0 11 031",
        netcdf_name="vo",
        numerical_models=["IFS", "ARPEGE", "GFS"],
        references=["Holton & Hakim (2012)"],
        dependencies=["wind_u", "wind_v"],
        related_laws=["absolute_vorticity", "vector_curl"],
        calculation_methods=["acf.science.dynamics"],
    ),
    PhysicalParameter(
        key="divergence",
        name="Divergence Horizontale du Vent",
        symbol="delta",
        domain="Dynamique",
        unit="s⁻¹",
        description="Taux d'étalement horizontal du champ de vitesse du fluide.",
        physical_meaning="La divergence en altitude provoque des mouvements verticaux ascendants (convection) par continuité.",
        abbreviation="DIV",
        category="Dynamique",
        dimensions="[T⁻¹]",
        governing_equation="delta = du/dx + dv/dy",
        latex_equation=r"\delta = \frac{\partial u}{\partial x} + \frac{\partial v}{\partial y}",
        valid_range="-1e-2 s⁻¹ to 1e-2 s⁻¹",
        cf_standard_name="divergence_of_wind",
        grib2_code="0,2,13",
        netcdf_name="div",
        numerical_models=["IFS", "ARPEGE", "GFS"],
        references=["Holton & Hakim (2012)"],
        dependencies=["wind_u", "wind_v"],
        related_laws=["vector_divergence", "mass_conservation"],
        calculation_methods=["acf.science.divergence.Divergence.calculate"],
    ),
    PhysicalParameter(
        key="potential_vorticity",
        name="Vorticité Potentielle d'Ertel",
        symbol="PV",
        domain="Dynamique",
        unit="PVU",
        description="Produit scalaire du vecteur vorticité absolue et du gradient de température potentielle.",
        physical_meaning="Grandeur dynamique conservée sous processus adiabatiques, traceur des anomalies de la tropopause.",
        abbreviation="PV",
        category="Dynamique",
        alternative_units=["10⁻⁶ K m² kg⁻¹ s⁻¹"],
        dimensions="[M⁻¹ L² T⁻¹ K]",
        governing_equation="PV = (1 / rho) * (zeta + f) * (dtheta / dz)",
        latex_equation=r"PV = \frac{1}{\rho} (\zeta + f) \frac{\partial \theta}{\partial z}",
        valid_range="-20 PVU to 20 PVU",
        cf_standard_name="ertels_potential_vorticity",
        grib2_code="0,2,14",
        netcdf_name="pv",
        numerical_models=["IFS", "ARPEGE", "GFS", "ICON"],
        references=["Ertel (1942)", "Hoskins et al. (1985)"],
        dependencies=["vorticity", "potential_temperature", "density"],
        related_laws=["ertel_potential_vorticity"],
        calculation_methods=["acf.science.potential_vorticity"],
    ),
    PhysicalParameter(
        key="deformation",
        name="Déformation du Champ de Vent",
        symbol="D_def",
        domain="Dynamique",
        unit="s⁻¹",
        description="Taux d'étirement et de cisaillement du champ de vent sans changement de surface.",
        physical_meaning="Moteur principal de la frontogenèse atmosphérique et du resserrement des gradients thermiques.",
        abbreviation="DEF",
        category="Dynamique",
        dimensions="[T⁻¹]",
        valid_range="0 to 1e-2 s⁻¹",
        cf_standard_name="wind_deformation",
        netcdf_name="def",
        numerical_models=["ARPEGE", "GFS"],
        references=["Holton & Hakim (2012)"],
        dependencies=["wind_u", "wind_v"],
        related_laws=["vector_gradient"],
        calculation_methods=["acf.science.frontogenesis"],
    ),
    # ----------------------------------------------------
    # THERMODYNAMICS
    # ----------------------------------------------------
    PhysicalParameter(
        key="potential_temperature",
        name="Température Potentielle",
        symbol="theta",
        domain="Thermodynamique",
        unit="K",
        description="Température qu'aurait une parcelle amenée adiabatiquement à 1000 hPa.",
        physical_meaning="Indicateur de la stabilité statique dry-adiabatic de l'atmosphère (dtheta/dz > 0 est stable).",
        abbreviation="POT",
        category="Thermodynamique",
        alternative_units=["°C"],
        dimensions="[K]",
        governing_equation="theta = T * (1000 / p)^0.286",
        latex_equation=r"\theta = T \left(\frac{p_0}{p}\right)^{\frac{R_d}{c_p}}",
        valid_range="200 K to 450 K",
        cf_standard_name="air_potential_temperature",
        grib2_code="0,0,2",
        bufr_code="0 12 003",
        netcdf_name="theta",
        numerical_models=["IFS", "AROME", "ARPEGE", "WRF"],
        references=["Poisson (1823)", "WMO"],
        dependencies=["temperature", "pressure"],
        related_laws=["potential_temperature", "adiabatic_transformation"],
        calculation_methods=["acf.science.potential_temperature.PotentialTemperature.calculate"],
    ),
    PhysicalParameter(
        key="equivalent_potential_temperature",
        name="Température Potentielle Équivalente",
        symbol="theta_e",
        domain="Thermodynamique",
        unit="K",
        description="Température potentielle après condensation totale et libération de toute la chaleur latente.",
        physical_meaning="Mesure l'énergie enthalpique totale (chaleur sensible + vapeur d'eau) contenue dans la masse d'air.",
        abbreviation="THETAE",
        category="Thermodynamique",
        alternative_units=["°C"],
        dimensions="[K]",
        governing_equation="theta_e = theta * exp(L_v * q / (c_p * T))",
        latex_equation=r"\theta_e \approx \theta \exp\left(\frac{L_v q}{c_p T}\right)",
        valid_range="240 K to 420 K",
        cf_standard_name="equivalent_potential_temperature",
        grib2_code="0,0,3",
        netcdf_name="thetae",
        numerical_models=["AROME", "WRF", "Meso-NH"],
        references=["Bolton (1980) Mon. Wea. Rev."],
        dependencies=["potential_temperature", "humidity"],
        related_laws=["first_law_thermodynamics", "clausius_clapeyron"],
        calculation_methods=["acf.science.equivalent_potential_temperature"],
    ),
    PhysicalParameter(
        key="CAPE",
        name="Énergie Potentielle Convective Disponible (CAPE)",
        symbol="CAPE",
        domain="Thermodynamique",
        unit="J/kg",
        description="Intégrale de la force de flottabilité positive exercée sur une parcelle d'air ascendante.",
        physical_meaning="Potentiel d'accélération verticale des courants ascendants lors d'orages violents.",
        abbreviation="CAPE",
        category="Convection & Severe Storms",
        alternative_units=["m²/s²"],
        dimensions="[L² T⁻²]",
        governing_equation="CAPE = int_LFC^EL g * ((T_v_parcel - T_v_env) / T_v_env) dz",
        latex_equation=r"\text{CAPE} = \int_{z_{\text{LFC}}}^{z_{\text{EL}}} g \frac{T_{v,\text{parcel}} - T_{v,\text{env}}}{T_{v,\text{env}}} dz",
        valid_range="0 J/kg to 6000 J/kg",
        cf_standard_name="atmosphere_convective_available_potential_energy",
        grib2_code="0,7,6",
        bufr_code="0 13 015",
        netcdf_name="cape",
        observation_systems=["Radiosondage", "Profil de température et humidité"],
        numerical_models=["AROME", "WRF", "IFS", "ICON", "GFS"],
        aviation_applications=["Risque de grêle et turbulence orageuse sévère"],
        references=["Moncrieff & Miller (1976)", "NOAA SPC Manual"],
        dependencies=["temperature", "humidity", "pressure"],
        related_laws=["first_law_thermodynamics", "hydrostatic_equilibrium"],
        calculation_methods=["acf.science.cape.CAPE.calculate"],
    ),
    PhysicalParameter(
        key="CIN",
        name="Inhibition Convective (CIN)",
        symbol="CIN",
        domain="Thermodynamique",
        unit="J/kg",
        description="Énergie négative nécessaire pour élever une parcelle du sol jusqu'au niveau de libre convection (LFC).",
        physical_meaning="Barrière d'inversion thermique bloquant le déclenchement prématuré de la convection.",
        abbreviation="CIN",
        category="Convection & Severe Storms",
        alternative_units=["m²/s²"],
        dimensions="[L² T⁻²]",
        governing_equation="CIN = int_SFC^LFC g * ((T_v_parcel - T_v_env) / T_v_env) dz",
        latex_equation=r"\text{CIN} = \int_{z_{\text{SFC}}}^{z_{\text{LFC}}} g \frac{T_{v,\text{parcel}} - T_{v,\text{env}}}{T_{v,\text{env}}} dz",
        valid_range="-1000 J/kg to 0 J/kg",
        cf_standard_name="atmosphere_convective_inhibition",
        grib2_code="0,7,7",
        bufr_code="0 13 016",
        netcdf_name="cin",
        numerical_models=["AROME", "WRF", "IFS", "ICON"],
        references=["NOAA SPC Manual"],
        dependencies=["temperature", "humidity", "pressure"],
        related_laws=["first_law_thermodynamics"],
        calculation_methods=["acf.science.cin.CIN.calculate"],
    ),
    # ----------------------------------------------------
    # MICROPHYSICS & CLOUDS
    # ----------------------------------------------------
    PhysicalParameter(
        key="cloud_water",
        name="Eau Liquide Nuageuse",
        symbol="qc",
        domain="Microphysique",
        unit="kg/kg",
        description="Rapport de mélange des gouttelettes d'eau condensées en suspension.",
        physical_meaning="Masse d'eau liquide maintenue en suspension par la traînée de l'air avant précipitation.",
        abbreviation="CLW",
        category="Nuages & Hydrométéores",
        alternative_units=["g/kg", "g/m³"],
        dimensions="[M M⁻¹]",
        valid_range="0 kg/kg to 0.01 kg/kg",
        cf_standard_name="mass_fraction_of_cloud_liquid_water_in_air",
        grib2_code="0,1,83",
        netcdf_name="clw",
        numerical_models=["AROME", "WRF", "ICE3", "ICE4", "WDM6", "IFS"],
        satellite_products=["SEVIRI Cloud Water Path (CWP)"],
        references=["Kessler (1969)", "Pruppacher & Klett (1997)"],
        dependencies=["humidity", "temperature"],
        related_laws=["kessler_autoconversion"],
        calculation_methods=["acf.model4d.physics.atmospheric_cloud_microphysics"],
    ),
    PhysicalParameter(
        key="rain_water",
        name="Eau de Pluie",
        symbol="qr",
        domain="Microphysique",
        unit="kg/kg",
        description="Rapport de mélange des gouttes de pluie précipitantes.",
        physical_meaning="Masse d'eau liquide tombant sous l'effet de la gravité.",
        abbreviation="RW",
        category="Nuages & Hydrométéores",
        alternative_units=["g/kg"],
        dimensions="[M M⁻¹]",
        valid_range="0 kg/kg to 0.02 kg/kg",
        cf_standard_name="mass_fraction_of_rain_in_air",
        grib2_code="0,1,85",
        netcdf_name="rwm",
        numerical_models=["AROME", "WRF", "ICE3", "ICE4", "IFS"],
        radar_products=["Réflectivité ZH", "Débit de pluie QPE"],
        references=["Marshall & Palmer (1948)"],
        dependencies=["cloud_water"],
        related_laws=["collection_coalescence"],
        calculation_methods=["acf.model4d.physics.atmospheric_cloud_microphysics"],
    ),
    PhysicalParameter(
        key="ice",
        name="Glace Nuageuse",
        symbol="qi",
        domain="Microphysique",
        unit="kg/kg",
        description="Rapport de mélange des cristaux de glace primaires.",
        physical_meaning="Phase solide des nuages hauts (cirrus) et des sommets d'orages.",
        abbreviation="CICE",
        category="Nuages & Hydrométéores",
        alternative_units=["g/kg"],
        dimensions="[M M⁻¹]",
        valid_range="0 kg/kg to 0.005 kg/kg",
        cf_standard_name="mass_fraction_of_cloud_ice_in_air",
        grib2_code="0,1,84",
        netcdf_name="cli",
        numerical_models=["AROME", "WRF", "ICE3", "ICE4", "IFS"],
        satellite_products=["Cloud Ice Water Path (IWP)"],
        references=["Thompson et al. (2008)"],
        dependencies=["temperature", "cloud_water"],
        related_laws=["ice_crystal_nucleation"],
        calculation_methods=["acf.model4d.physics.atmospheric_cloud_microphysics"],
    ),
    PhysicalParameter(
        key="snow",
        name="Neige",
        symbol="qs",
        domain="Microphysique",
        unit="kg/kg",
        description="Rapport de mélange des agrégats de cristaux de neige précipitant.",
        physical_meaning="Hydrométéore solide tombant à faible vitesse limite de chute.",
        abbreviation="SNOW",
        category="Nuages & Hydrométéores",
        alternative_units=["g/kg"],
        dimensions="[M M⁻¹]",
        valid_range="0 kg/kg to 0.01 kg/kg",
        cf_standard_name="mass_fraction_of_snow_in_air",
        grib2_code="0,1,86",
        netcdf_name="snw",
        numerical_models=["AROME", "WRF", "ICE3", "ICE4", "IFS"],
        references=["Lin et al. (1983)"],
        dependencies=["ice", "temperature"],
        related_laws=["ice_crystal_nucleation"],
        calculation_methods=["acf.model4d.physics.atmospheric_cloud_microphysics"],
    ),
    PhysicalParameter(
        key="graupel",
        name="Grésil / Grêle",
        symbol="qg",
        domain="Microphysique",
        unit="kg/kg",
        description="Rapport de mélange des billes de glace dense formées par givrage.",
        physical_meaning="Précipitation solide dense associée à des courants ascendants très intenses.",
        abbreviation="GRPL",
        category="Nuages & Hydrométéores",
        alternative_units=["g/kg"],
        dimensions="[M M⁻¹]",
        valid_range="0 kg/kg to 0.02 kg/kg",
        cf_standard_name="mass_fraction_of_graupel_in_air",
        grib2_code="0,1,225",
        netcdf_name="grpl",
        numerical_models=["AROME", "WRF", "ICE3", "ICE4", "Meso-NH"],
        radar_products=["Dual-Pol ZDR", "KDP"],
        references=["Rutledge & Hobbs (1984)"],
        dependencies=["rain_water", "ice"],
        related_laws=["collection_coalescence"],
        calculation_methods=["acf.model4d.physics.atmospheric_cloud_microphysics"],
    ),
    # ----------------------------------------------------
    # RADIATION
    # ----------------------------------------------------
    PhysicalParameter(
        key="solar_flux",
        name="Flux Solaire Incident (Ondes Courtes)",
        symbol="F_sol",
        domain="Rayonnement",
        unit="W/m²",
        description="Énergie électromagnétique d'origine solaire reçue par unité de surface.",
        physical_meaning="Source primaire d'énergie réchauffant la surface terrestre et l'atmosphère.",
        abbreviation="DSWRF",
        category="Rayonnement",
        alternative_units=["W m⁻²"],
        dimensions="[M T⁻³]",
        valid_range="0 W/m² to 1361 W/m²",
        cf_standard_name="surface_downwelling_shortwave_flux_in_air",
        grib2_code="0,4,7",
        netcdf_name="rsds",
        numerical_models=["IFS", "AROME", "ICON", "GFS"],
        references=["Planck (1900)", "Liou (2002)"],
        dependencies=["temperature"],
        related_laws=["planck_law", "beer_lambert"],
        calculation_methods=["acf.model4d.physics.atmospheric_radiation_dynamics"],
    ),
    PhysicalParameter(
        key="infrared_flux",
        name="Flux Infrarouge Terrestre (Ondes Longues)",
        symbol="F_IR",
        domain="Rayonnement",
        unit="W/m²",
        description="Énergie électromagnétique Infrarouge émise par la Terre et l'atmosphère.",
        physical_meaning="Refroidissement radiatif de la planète compensé par l'effet de serre.",
        abbreviation="DLWRF",
        category="Rayonnement",
        alternative_units=["W m⁻²"],
        dimensions="[M T⁻³]",
        valid_range="100 W/m² to 700 W/m²",
        cf_standard_name="surface_downwelling_longwave_flux_in_air",
        grib2_code="0,5,3",
        netcdf_name="rlds",
        numerical_models=["IFS", "AROME", "ICON", "GFS"],
        references=["Stefan (1879)", "Boltzmann (1884)"],
        dependencies=["temperature"],
        related_laws=["stefan_boltzmann"],
        calculation_methods=["acf.model4d.physics.atmospheric_radiation_dynamics"],
    ),
    PhysicalParameter(
        key="albedo",
        name="Albédo de Surface",
        symbol="alpha",
        domain="Rayonnement",
        unit="dimensionless",
        description="Fraction du rayonnement solaire incident réfléchie par la surface.",
        physical_meaning="Détermine la quantité d'énergie solaire absorbée par le sol (neige ~ 0.8, océan ~ 0.06).",
        abbreviation="ALB",
        category="Rayonnement",
        dimensions="[1]",
        valid_range="0 to 1.0",
        cf_standard_name="surface_albedo",
        grib2_code="0,19,1",
        netcdf_name="alb",
        numerical_models=["IFS", "AROME", "SURFEX", "ICON"],
        satellite_products=["MODIS Albedo Product", "SEVIRI Albedo"],
        references=["Liou (2002)"],
        dependencies=["solar_flux"],
        related_laws=["beer_lambert"],
        calculation_methods=["acf.model4d.physics.atmospheric_radiation_dynamics"],
    ),
    # ----------------------------------------------------
    # AERONAUTICS
    # ----------------------------------------------------
    PhysicalParameter(
        key="density_altitude",
        name="Altitude-Densité",
        symbol="DA",
        domain="Aéronautique",
        unit="ft",
        description="Altitude en atmosphère standard ISA correspondant à la densité actuelle de l'air.",
        physical_meaning="Critère déterminant les performances de décollage, la longueur de roulement et le taux de montée d'un avion.",
        abbreviation="DA",
        category="Météorologie Aéronautique",
        alternative_units=["m"],
        dimensions="[L]",
        governing_equation="DA = PA + 120 * (OAT - ISA_Temp)",
        latex_equation=r"\text{DA} = \text{PA} + 120 (T_{\text{reelle}} - T_{\text{ISA}})",
        valid_range="-2000 ft to 20000 ft",
        aviation_applications=["Performances de décollage", "Centrage et charge utile"],
        references=["ICAO Doc 8335", "FAA Handbook"],
        dependencies=["temperature", "pressure"],
        related_laws=["density_altitude_aviation"],
        calculation_methods=["acf.science.encyclopedia.aviation_extended.calculate_density_altitude"],
    ),
    PhysicalParameter(
        key="speed_of_sound",
        name="Vitesse du Son dans l'Air",
        symbol="a",
        domain="Aéronautique",
        unit="m/s",
        description="Vitesse de propagation des ondes de compression acoustique.",
        physical_meaning="Référence pour l'écoulement compressible autour des aéronefs.",
        abbreviation="SON",
        category="Aéronautique",
        alternative_units=["km/h", "knots"],
        dimensions="[L T⁻¹]",
        governing_equation="a = sqrt(gamma * R_d * T)",
        latex_equation=r"a = \sqrt{\gamma R_d T}",
        valid_range="250 m/s to 350 m/s",
        cf_standard_name="speed_of_sound_in_air",
        aviation_applications=["Vitesse Mach"],
        references=["ICAO Doc 7488"],
        dependencies=["temperature"],
        related_laws=["speed_of_sound"],
        calculation_methods=["acf.science.laws.aeronautics"],
    ),
    PhysicalParameter(
        key="mach",
        name="Nombre de Mach",
        symbol="M",
        domain="Aéronautique",
        unit="dimensionless",
        description="Rapport entre la vitesse vraie de l'aéronef et la vitesse locale du son.",
        physical_meaning="Régime de vol (subsonique, transsonique, supersonique).",
        abbreviation="MACH",
        category="Aéronautique",
        dimensions="[1]",
        governing_equation="M = V / a",
        latex_equation=r"M = \frac{V}{a}",
        valid_range="0 to 3.0",
        aviation_applications=["Vitesse de vol de croisière jet"],
        references=["ICAO Docs"],
        dependencies=["wind_u", "speed_of_sound"],
        related_laws=["mach_number"],
        calculation_methods=["acf.science.laws.aeronautics"],
    ),
    PhysicalParameter(
        key="reynolds",
        name="Nombre de Reynolds",
        symbol="Re",
        domain="Aéronautique",
        unit="dimensionless",
        description="Rapport des forces d'inertie aux forces de viscosité.",
        physical_meaning="Détermine le régime de la couche limite aérodynamique (laminaire ou turbulent).",
        abbreviation="RE",
        category="Aéronautique",
        dimensions="[1]",
        governing_equation="Re = (rho * V * L) / mu",
        latex_equation=r"Re = \frac{\rho V L}{\mu}",
        valid_range="1e2 to 1e8",
        references=["Prandtl (1925)", "ICAO Docs"],
        dependencies=["density", "wind_u"],
        related_laws=["reynolds_number"],
        calculation_methods=["acf.science.laws.aeronautics"],
    ),
    PhysicalParameter(
        key="lift_coefficient",
        name="Coefficient de Portance",
        symbol="CL",
        domain="Aéronautique",
        unit="dimensionless",
        description="Coefficient adimensionnel de la force de portance générée par la voilure.",
        physical_meaning="Dépend de l'angle d'attaque de l'aile et du profil aérodynamique.",
        abbreviation="CL",
        category="Aéronautique",
        dimensions="[1]",
        governing_equation="CL = L / (0.5 * rho * V^2 * S)",
        latex_equation=r"C_L = \frac{L}{\frac{1}{2} \rho V^2 S}",
        valid_range="0 to 2.5",
        aviation_applications=["Décrochage aérodynamique (Stall)"],
        references=["ICAO Docs"],
        dependencies=["density", "wind_u"],
        related_laws=["aerodynamic_lift"],
        calculation_methods=["acf.science.laws.aeronautics"],
    ),
    PhysicalParameter(
        key="drag_coefficient",
        name="Coefficient de Traînée",
        symbol="CD",
        domain="Aéronautique",
        unit="dimensionless",
        description="Coefficient adimensionnel de la force de résistance à l'avancement.",
        physical_meaning="Somme de la traînée de forme, de frottement et induite.",
        abbreviation="CD",
        category="Aéronautique",
        dimensions="[1]",
        governing_equation="CD = D / (0.5 * rho * V^2 * S)",
        latex_equation=r"C_D = \frac{D}{\frac{1}{2} \rho V^2 S}",
        valid_range="0.01 to 1.5",
        aviation_applications=["Consommation de carburant"],
        references=["ICAO Docs"],
        dependencies=["density", "wind_u"],
        related_laws=["aerodynamic_drag"],
        calculation_methods=["acf.science.laws.aeronautics"],
    ),
    # ----------------------------------------------------
    # REMOTE SENSING & RADAR
    # ----------------------------------------------------
    PhysicalParameter(
        key="radar_zdr",
        name="Réflectivité Différentielle Radar",
        symbol="ZDR",
        domain="Télédétection Atmosphérique",
        unit="dB",
        description="Rapport de la réflectivité en polarisation horizontale sur la polarisation verticale.",
        physical_meaning="Mesure l'oblatié moyenne des gouttes d'eau et distingue la pluie de la grêle sphérique.",
        abbreviation="ZDR",
        category="Radar & Télédétection",
        alternative_units=["ratio"],
        dimensions="[1]",
        governing_equation="ZDR = 10 * log10(Zh / Zv)",
        latex_equation=r"Z_{\text{DR}} = 10 \log_{10}\left(\frac{Z_H}{Z_V}\right)",
        valid_range="-2 dB to 8 dB",
        observation_systems=["Radar Météorologique Double Polarisation"],
        radar_products=["ZDR", "HydroClass (HCA)"],
        references=["Bringi & Chandrasekar (2001)"],
        dependencies=[],
        related_laws=["polarimetric_radar_zdr"],
        calculation_methods=["acf.science.encyclopedia.remote_sensing_extended.calculate_radar_zdr"],
    ),
]
